// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4model1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4stan_1_SAR_NASC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4stan_1_SDM_NASC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4stan_2_NASC_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4model1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model1_mod, 0},
    {"_rcpp_module_boot_stan_fit4stan_1_SAR_NASC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4stan_1_SAR_NASC_mod, 0},
    {"_rcpp_module_boot_stan_fit4stan_1_SDM_NASC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4stan_1_SDM_NASC_mod, 0},
    {"_rcpp_module_boot_stan_fit4stan_2_NASC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4stan_2_NASC_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_nasc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
