// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stan_1_SDM_NASC_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 63> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 42, column 2 to column 30)",
  " (in 'string', line 43, column 2 to column 22)",
  " (in 'string', line 44, column 2 to column 23)",
  " (in 'string', line 45, column 2 to column 26)",
  " (in 'string', line 51, column 2 to column 27)",
  " (in 'string', line 52, column 2 to column 22)",
  " (in 'string', line 53, column 2 to column 23)",
  " (in 'string', line 56, column 2 to column 48)",
  " (in 'string', line 57, column 2 to column 27)",
  " (in 'string', line 59, column 9 to column 14)",
  " (in 'string', line 59, column 16 to column 18)",
  " (in 'string', line 59, column 2 to column 54)",
  " (in 'string', line 61, column 9 to column 14)",
  " (in 'string', line 61, column 2 to column 67)",
  " (in 'string', line 63, column 2 to column 88)",
  " (in 'string', line 5, column 2 to column 22)",
  " (in 'string', line 6, column 9 to column 15)",
  " (in 'string', line 6, column 2 to column 20)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 9 to column 15)",
  " (in 'string', line 8, column 17 to column 18)",
  " (in 'string', line 8, column 2 to column 23)",
  " (in 'string', line 9, column 2 to column 18)",
  " (in 'string', line 10, column 9 to column 14)",
  " (in 'string', line 10, column 16 to column 18)",
  " (in 'string', line 10, column 2 to column 28)",
  " (in 'string', line 11, column 9 to column 14)",
  " (in 'string', line 11, column 16 to column 21)",
  " (in 'string', line 11, column 2 to column 25)",
  " (in 'string', line 12, column 9 to column 14)",
  " (in 'string', line 12, column 2 to column 25)",
  " (in 'string', line 16, column 9 to column 14)",
  " (in 'string', line 16, column 16 to column 22)",
  " (in 'string', line 16, column 2 to column 35)",
  " (in 'string', line 17, column 9 to column 14)",
  " (in 'string', line 17, column 16 to column 22)",
  " (in 'string', line 17, column 2 to column 35)",
  " (in 'string', line 19, column 4 to column 44)",
  " (in 'string', line 20, column 4 to column 33)",
  " (in 'string', line 22, column 4 to column 40)",
  " (in 'string', line 23, column 4 to column 36)",
  " (in 'string', line 25, column 4 to column 56)",
  " (in 'string', line 18, column 22 to line 26, column 3)",
  " (in 'string', line 18, column 2 to line 26, column 3)",
  " (in 'string', line 28, column 9 to column 14)",
  " (in 'string', line 28, column 16 to column 18)",
  " (in 'string', line 28, column 2 to column 32)",
  " (in 'string', line 29, column 2 to column 41)",
  " (in 'string', line 30, column 2 to column 37)",
  " (in 'string', line 33, column 6 to column 58)",
  " (in 'string', line 32, column 20 to line 34, column 5)",
  " (in 'string', line 32, column 4 to line 34, column 5)",
  " (in 'string', line 31, column 23 to line 35, column 3)",
  " (in 'string', line 31, column 2 to line 35, column 3)",
  " (in 'string', line 38, column 9 to column 14)",
  " (in 'string', line 38, column 16 to column 18)",
  " (in 'string', line 38, column 2 to column 47)",
  " (in 'string', line 39, column 9 to column 14)",
  " (in 'string', line 39, column 16 to column 22)",
  " (in 'string', line 39, column 2 to column 53)",
  " (in 'string', line 43, column 9 to column 15)",
  " (in 'string', line 44, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_stan_1_SDM_NASC final : public model_base_crtp<model_stan_1_SDM_NASC> {
private:
  int K_pred;
  Eigen::Matrix<double,-1,1> X1_data__;
  int J;
  Eigen::Matrix<double,-1,-1> X0_data__;
  int T0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_data__;
  Eigen::Matrix<double,-1,1> lambda_W_data__;
  Eigen::Matrix<double,-1,-1> X_full_raw_data__;
  Eigen::Matrix<double,-1,-1> X_full_std_data__;
  Eigen::Matrix<double,-1,-1> Y_panel_std_data__;
  double mean_y;
  double sd_y;
  Eigen::Matrix<double,-1,-1> WY_panel_data__;
  Eigen::Matrix<double,-1,-1> WX_full_std_data__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> X1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X0{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> lambda_W{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_full_raw{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_full_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> WY_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> WX_full_std{nullptr, 0, 0};
public:
  ~model_stan_1_SDM_NASC() {}
  model_stan_1_SDM_NASC(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::model_stan_1_SDM_NASC";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 16;
      context__.validate_dims("data initialization", "K_pred", "int",
        std::vector<size_t>{});
      K_pred = std::numeric_limits<int>::min();
      current_statement__ = 16;
      K_pred = context__.vals_i("K_pred")[(1 - 1)];
      current_statement__ = 16;
      stan::math::check_greater_or_equal(function__, "K_pred", K_pred, 1);
      current_statement__ = 17;
      stan::math::validate_non_negative_index("X1", "K_pred", K_pred);
      current_statement__ = 18;
      context__.validate_dims("data initialization", "X1", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      X1_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X1) Eigen::Map<Eigen::Matrix<double,-1,1>>(X1_data__.data(),
        K_pred);
      {
        std::vector<local_scalar_t__> X1_flat__;
        current_statement__ = 18;
        X1_flat__ = context__.vals_r("X1");
        current_statement__ = 18;
        pos__ = 1;
        current_statement__ = 18;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 18;
          stan::model::assign(X1, X1_flat__[(pos__ - 1)],
            "assigning variable X1", stan::model::index_uni(sym1__));
          current_statement__ = 18;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 19;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 19;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("X0", "K_pred", K_pred);
      current_statement__ = 21;
      stan::math::validate_non_negative_index("X0", "J", J);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "X0", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred),
          static_cast<size_t>(J)});
      X0_data__ = Eigen::Matrix<double,-1,-1>::Constant(K_pred, J,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X0) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X0_data__.data(),
        K_pred, J);
      {
        std::vector<local_scalar_t__> X0_flat__;
        current_statement__ = 22;
        X0_flat__ = context__.vals_r("X0");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 22;
          for (int sym2__ = 1; sym2__ <= K_pred; ++sym2__) {
            current_statement__ = 22;
            stan::model::assign(X0, X0_flat__[(pos__ - 1)],
              "assigning variable X0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 22;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 23;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 23;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 25;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 26;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 26;
        pos__ = 1;
        current_statement__ = 26;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 26;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 26;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 26;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 27;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 28;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 29;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>((J + 1))});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), (J + 1),
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), (J +
        1), (J + 1));
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 29;
        W_flat__ = context__.vals_r("W");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 29;
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 29;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("lambda_W", "J + 1", (J + 1));
      current_statement__ = 31;
      context__.validate_dims("data initialization", "lambda_W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1))});
      lambda_W_data__ = Eigen::Matrix<double,-1,1>::Constant((J + 1),
                          std::numeric_limits<double>::quiet_NaN());
      new (&lambda_W)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(lambda_W_data__.data(), (J +
        1));
      {
        std::vector<local_scalar_t__> lambda_W_flat__;
        current_statement__ = 31;
        lambda_W_flat__ = context__.vals_r("lambda_W");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(lambda_W, lambda_W_flat__[(pos__ - 1)],
            "assigning variable lambda_W", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("X_full_raw", "J + 1", (J + 1));
      current_statement__ = 33;
      stan::math::validate_non_negative_index("X_full_raw", "K_pred", K_pred);
      current_statement__ = 34;
      X_full_raw_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1),
                            K_pred, std::numeric_limits<double>::quiet_NaN());
      new (&X_full_raw)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_full_raw_data__.data(), (J
        + 1), K_pred);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("X_full_std", "J + 1", (J + 1));
      current_statement__ = 36;
      stan::math::validate_non_negative_index("X_full_std", "K_pred", K_pred);
      current_statement__ = 37;
      X_full_std_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1),
                            K_pred, std::numeric_limits<double>::quiet_NaN());
      new (&X_full_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_full_std_data__.data(), (J
        + 1), K_pred);
      current_statement__ = 44;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 38;
        stan::model::assign(X_full_raw,
          stan::math::to_vector(
            stan::model::rvalue(X0, "X0", stan::model::index_uni(k),
              stan::model::index_omni())), "assigning variable X_full_raw",
          stan::model::index_min_max(1, J), stan::model::index_uni(k));
        current_statement__ = 39;
        stan::model::assign(X_full_raw,
          stan::model::rvalue(X1, "X1", stan::model::index_uni(k)),
          "assigning variable X_full_raw", stan::model::index_uni((J + 1)),
          stan::model::index_uni(k));
        double mean_k = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 40;
        mean_k = stan::math::mean(
                   stan::model::rvalue(X_full_raw, "X_full_raw",
                     stan::model::index_omni(), stan::model::index_uni(k)));
        double sd_k = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 41;
        sd_k = stan::math::sd(
                 stan::model::rvalue(X_full_raw, "X_full_raw",
                   stan::model::index_omni(), stan::model::index_uni(k)));
        current_statement__ = 42;
        stan::model::assign(X_full_std,
          stan::math::divide(
            stan::math::subtract(
              stan::model::rvalue(X_full_raw, "X_full_raw",
                stan::model::index_omni(), stan::model::index_uni(k)), mean_k),
            sd_k), "assigning variable X_full_std",
          stan::model::index_omni(), stan::model::index_uni(k));
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("Y_panel_std", "J + 1", (J + 1));
      current_statement__ = 46;
      stan::math::validate_non_negative_index("Y_panel_std", "T0", T0);
      current_statement__ = 47;
      Y_panel_std_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                             std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_std_data__.data(), (J
        + 1), T0);
      current_statement__ = 48;
      mean_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 48;
      mean_y = stan::math::mean(stan::math::to_vector(Y_panel));
      current_statement__ = 49;
      sd_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      sd_y = stan::math::sd(stan::math::to_vector(Y_panel));
      current_statement__ = 54;
      for (int j = 1; j <= (J + 1); ++j) {
        current_statement__ = 52;
        for (int t = 1; t <= T0; ++t) {
          current_statement__ = 50;
          stan::model::assign(Y_panel_std,
            ((stan::model::rvalue(Y_panel, "Y_panel",
                stan::model::index_uni(j), stan::model::index_uni(t)) -
            mean_y) / sd_y), "assigning variable Y_panel_std",
            stan::model::index_uni(j), stan::model::index_uni(t));
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("WY_panel", "J + 1", (J + 1));
      current_statement__ = 56;
      stan::math::validate_non_negative_index("WY_panel", "T0", T0);
      current_statement__ = 57;
      WY_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                          std::numeric_limits<double>::quiet_NaN());
      new (&WY_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(WY_panel_data__.data(), (J +
        1), T0);
      current_statement__ = 57;
      stan::model::assign(WY_panel, stan::math::multiply(W, Y_panel_std),
        "assigning variable WY_panel");
      current_statement__ = 58;
      stan::math::validate_non_negative_index("WX_full_std", "J + 1", (J + 1));
      current_statement__ = 59;
      stan::math::validate_non_negative_index("WX_full_std", "K_pred", K_pred);
      current_statement__ = 60;
      WX_full_std_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1),
                             K_pred,
                             std::numeric_limits<double>::quiet_NaN());
      new (&WX_full_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(WX_full_std_data__.data(), (J
        + 1), K_pred);
      current_statement__ = 60;
      stan::model::assign(WX_full_std, stan::math::multiply(W, X_full_std),
        "assigning variable WX_full_std");
      current_statement__ = 61;
      stan::math::validate_non_negative_index("beta", "K_pred", K_pred);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("theta", "K_pred", K_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + K_pred + K_pred + 1;
  }
  inline std::string model_name() const final {
    return "model_stan_1_SDM_NASC";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 3;
      theta = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_sdm, 0, 1));
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(theta, 0, 1));
        local_scalar_t__ log_det_A = DUMMY_VAR__;
        current_statement__ = 8;
        log_det_A = stan::math::sum(
                      stan::math::log(
                        stan::math::subtract(1,
                          stan::math::multiply(rho, lambda_W))));
        current_statement__ = 9;
        lp_accum__.add((T0 * log_det_A));
        current_statement__ = 10;
        stan::math::validate_non_negative_index("AY", "J + 1", (J + 1));
        current_statement__ = 11;
        stan::math::validate_non_negative_index("AY", "T0", T0);
        Eigen::Matrix<local_scalar_t__,-1,-1> AY =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant((J + 1), T0,
            DUMMY_VAR__);
        current_statement__ = 12;
        stan::model::assign(AY,
          stan::math::subtract(Y_panel_std,
            stan::math::multiply(rho, WY_panel)), "assigning variable AY");
        current_statement__ = 13;
        stan::math::validate_non_negative_index("sdm_mean", "J + 1", (J + 1));
        Eigen::Matrix<local_scalar_t__,-1,1> sdm_mean =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant((J + 1),
            DUMMY_VAR__);
        current_statement__ = 14;
        stan::model::assign(sdm_mean,
          stan::math::add(stan::math::multiply(X_full_std, beta),
            stan::math::multiply(WX_full_std, theta)),
          "assigning variable sdm_mean");
        current_statement__ = 15;
        lp_accum__.add(stan::math::normal_lpdf<false>(
                         stan::math::to_vector(AY),
                         stan::math::to_vector(
                           stan::math::rep_matrix(sdm_mean, T0)), sigma_sdm));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      theta = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      double sigma_sdm = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_sdm = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      out__.write(rho);
      out__.write(beta);
      out__.write(theta);
      out__.write(sigma_sdm);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable theta");
      out__.write(theta);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sdm);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_sdm",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 3;
        theta_flat__ = context__.vals_r("theta");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(theta);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = context__.vals_r("sigma_sdm")[(1 - 1)];
      out__.write_free_lb(0, sigma_sdm);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"rho", "beta", "theta", "sigma_sdm"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sdm");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sdm");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sdm\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sdm\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + K_pred) + K_pred) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + K_pred) + K_pred) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stan_1_SDM_NASC_namespace::model_stan_1_SDM_NASC;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stan_1_SDM_NASC_namespace::profiles__;
}
#endif
#endif
