// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_nasc_SAR_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 97> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 43, column 2 to column 30)",
  " (in 'string', line 44, column 2 to column 22)",
  " (in 'string', line 45, column 2 to column 19)",
  " (in 'string', line 46, column 2 to column 26)",
  " (in 'string', line 48, column 2 to column 15)",
  " (in 'string', line 49, column 2 to column 28)",
  " (in 'string', line 50, column 2 to column 25)",
  " (in 'string', line 51, column 2 to column 23)",
  " (in 'string', line 55, column 2 to column 58)",
  " (in 'string', line 56, column 2 to column 23)",
  " (in 'string', line 88, column 2 to column 26)",
  " (in 'string', line 89, column 2 to column 57)",
  " (in 'string', line 58, column 4 to column 39)",
  " (in 'string', line 57, column 22 to line 59, column 3)",
  " (in 'string', line 57, column 2 to line 59, column 3)",
  " (in 'string', line 91, column 4 to column 64)",
  " (in 'string', line 92, column 4 to column 47)",
  " (in 'string', line 90, column 22 to line 93, column 3)",
  " (in 'string', line 90, column 2 to line 93, column 3)",
  " (in 'string', line 63, column 2 to column 23)",
  " (in 'string', line 64, column 2 to column 21)",
  " (in 'string', line 65, column 2 to column 27)",
  " (in 'string', line 66, column 2 to column 22)",
  " (in 'string', line 67, column 2 to column 26)",
  " (in 'string', line 68, column 2 to column 25)",
  " (in 'string', line 69, column 2 to column 28)",
  " (in 'string', line 72, column 11 to column 16)",
  " (in 'string', line 72, column 18 to column 23)",
  " (in 'string', line 72, column 4 to column 46)",
  " (in 'string', line 73, column 4 to column 40)",
  " (in 'string', line 75, column 11 to column 16)",
  " (in 'string', line 75, column 4 to column 52)",
  " (in 'string', line 77, column 6 to column 26)",
  " (in 'string', line 79, column 6 to column 68)",
  " (in 'string', line 76, column 20 to line 80, column 5)",
  " (in 'string', line 76, column 4 to line 80, column 5)",
  " (in 'string', line 71, column 2 to line 81, column 3)",
  " (in 'string', line 83, column 2 to column 46)",
  " (in 'string', line 85, column 2 to column 52)",
  " (in 'string', line 5, column 2 to column 22)",
  " (in 'string', line 6, column 9 to column 15)",
  " (in 'string', line 6, column 2 to column 20)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 9 to column 15)",
  " (in 'string', line 8, column 17 to column 18)",
  " (in 'string', line 8, column 2 to column 23)",
  " (in 'string', line 9, column 18 to column 24)",
  " (in 'string', line 9, column 2 to column 29)",
  " (in 'string', line 11, column 2 to column 18)",
  " (in 'string', line 12, column 9 to column 14)",
  " (in 'string', line 12, column 16 to column 18)",
  " (in 'string', line 12, column 2 to column 28)",
  " (in 'string', line 13, column 9 to column 14)",
  " (in 'string', line 13, column 16 to column 21)",
  " (in 'string', line 13, column 2 to column 25)",
  " (in 'string', line 15, column 9 to column 10)",
  " (in 'string', line 15, column 12 to column 13)",
  " (in 'string', line 15, column 2 to column 19)",
  " (in 'string', line 16, column 9 to column 10)",
  " (in 'string', line 16, column 2 to column 17)",
  " (in 'string', line 18, column 2 to column 22)",
  " (in 'string', line 19, column 9 to column 15)",
  " (in 'string', line 19, column 17 to column 18)",
  " (in 'string', line 19, column 2 to column 28)",
  " (in 'string', line 20, column 9 to column 15)",
  " (in 'string', line 20, column 2 to column 25)",
  " (in 'string', line 23, column 9 to column 10)",
  " (in 'string', line 23, column 12 to column 13)",
  " (in 'string', line 23, column 2 to column 53)",
  " (in 'string', line 24, column 9 to column 14)",
  " (in 'string', line 24, column 16 to column 21)",
  " (in 'string', line 24, column 2 to column 68)",
  " (in 'string', line 26, column 9 to column 15)",
  " (in 'string', line 26, column 17 to column 18)",
  " (in 'string', line 26, column 2 to column 27)",
  " (in 'string', line 27, column 9 to column 15)",
  " (in 'string', line 27, column 2 to column 24)",
  " (in 'string', line 29, column 4 to column 28)",
  " (in 'string', line 30, column 4 to column 33)",
  " (in 'string', line 31, column 4 to column 29)",
  " (in 'string', line 28, column 22 to line 32, column 3)",
  " (in 'string', line 28, column 2 to line 32, column 3)",
  " (in 'string', line 35, column 9 to column 14)",
  " (in 'string', line 35, column 16 to column 22)",
  " (in 'string', line 35, column 2 to column 35)",
  " (in 'string', line 37, column 4 to column 48)",
  " (in 'string', line 38, column 4 to column 37)",
  " (in 'string', line 36, column 22 to line 39, column 3)",
  " (in 'string', line 36, column 2 to line 39, column 3)",
  " (in 'string', line 44, column 9 to column 15)",
  " (in 'string', line 45, column 9 to column 14)",
  " (in 'string', line 48, column 10 to column 11)",
  " (in 'string', line 49, column 10 to column 16)",
  " (in 'string', line 55, column 9 to column 10)",
  " (in 'string', line 56, column 9 to column 15)",
  " (in 'string', line 88, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_nasc_SAR final : public model_base_crtp<model_nasc_SAR> {
private:
  int K_pred;
  Eigen::Matrix<double,-1,1> X1_data__;
  int J;
  Eigen::Matrix<double,-1,-1> X0_data__;
  Eigen::Matrix<double,-1,1> vs_data__;
  int T0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_data__;
  Eigen::Matrix<double,-1,-1> W_J_data__;
  Eigen::Matrix<double,-1,1> w_J1_data__;
  int T_post;
  Eigen::Matrix<double,-1,-1> Y0_post_data__;
  Eigen::Matrix<double,-1,1> Y1_post_data__;
  Eigen::Matrix<double,-1,-1> I_J_data__;
  Eigen::Matrix<double,-1,-1> I_full_data__;
  Eigen::Matrix<double,-1,-1> X0_std_data__;
  Eigen::Matrix<double,-1,1> X1_std_data__;
  Eigen::Matrix<double,-1,-1> X_full_std_data__;
  int mu_1dim__;
  Eigen::Map<Eigen::Matrix<double,-1,1>> X1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X0{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> vs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> w_J1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y0_post{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y1_post{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> I_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> I_full{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X0_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> X1_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_full_std{nullptr, 0, 0};
public:
  ~model_nasc_SAR() {}
  model_nasc_SAR(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_nasc_SAR_namespace::model_nasc_SAR";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 40;
      context__.validate_dims("data initialization", "K_pred", "int",
        std::vector<size_t>{});
      K_pred = std::numeric_limits<int>::min();
      current_statement__ = 40;
      K_pred = context__.vals_i("K_pred")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "K_pred", K_pred, 1);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("X1", "K_pred", K_pred);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "X1", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      X1_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X1) Eigen::Map<Eigen::Matrix<double,-1,1>>(X1_data__.data(),
        K_pred);
      {
        std::vector<local_scalar_t__> X1_flat__;
        current_statement__ = 42;
        X1_flat__ = context__.vals_r("X1");
        current_statement__ = 42;
        pos__ = 1;
        current_statement__ = 42;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 42;
          stan::model::assign(X1, X1_flat__[(pos__ - 1)],
            "assigning variable X1", stan::model::index_uni(sym1__));
          current_statement__ = 42;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 43;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 43;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("X0", "K_pred", K_pred);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("X0", "J", J);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "X0", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred),
          static_cast<size_t>(J)});
      X0_data__ = Eigen::Matrix<double,-1,-1>::Constant(K_pred, J,
                    std::numeric_limits<double>::quiet_NaN());
      new (&X0) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X0_data__.data(),
        K_pred, J);
      {
        std::vector<local_scalar_t__> X0_flat__;
        current_statement__ = 46;
        X0_flat__ = context__.vals_r("X0");
        current_statement__ = 46;
        pos__ = 1;
        current_statement__ = 46;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 46;
          for (int sym2__ = 1; sym2__ <= K_pred; ++sym2__) {
            current_statement__ = 46;
            stan::model::assign(X0, X0_flat__[(pos__ - 1)],
              "assigning variable X0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 46;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 47;
      stan::math::validate_non_negative_index("vs", "K_pred", K_pred);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "vs", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      vs_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                    std::numeric_limits<double>::quiet_NaN());
      new (&vs) Eigen::Map<Eigen::Matrix<double,-1,1>>(vs_data__.data(),
        K_pred);
      {
        std::vector<local_scalar_t__> vs_flat__;
        current_statement__ = 48;
        vs_flat__ = context__.vals_r("vs");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 48;
          stan::model::assign(vs, vs_flat__[(pos__ - 1)],
            "assigning variable vs", stan::model::index_uni(sym1__));
          current_statement__ = 48;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "vs", vs, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 49;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 51;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 52;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 52;
        pos__ = 1;
        current_statement__ = 52;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 52;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 52;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 52;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 53;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 54;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 55;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>((J + 1))});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), (J + 1),
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), (J +
        1), (J + 1));
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 55;
        W_flat__ = context__.vals_r("W");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 55;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 55;
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 55;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "W_J", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(J)});
      W_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&W_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_J_data__.data(),
        J, J);
      {
        std::vector<local_scalar_t__> W_J_flat__;
        current_statement__ = 58;
        W_J_flat__ = context__.vals_r("W_J");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 58;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 58;
            stan::model::assign(W_J, W_J_flat__[(pos__ - 1)],
              "assigning variable W_J", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 58;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 59;
      stan::math::validate_non_negative_index("w_J1", "J", J);
      current_statement__ = 60;
      context__.validate_dims("data initialization", "w_J1", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      w_J1_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                      std::numeric_limits<double>::quiet_NaN());
      new (&w_J1) Eigen::Map<Eigen::Matrix<double,-1,1>>(w_J1_data__.data(),
        J);
      {
        std::vector<local_scalar_t__> w_J1_flat__;
        current_statement__ = 60;
        w_J1_flat__ = context__.vals_r("w_J1");
        current_statement__ = 60;
        pos__ = 1;
        current_statement__ = 60;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 60;
          stan::model::assign(w_J1, w_J1_flat__[(pos__ - 1)],
            "assigning variable w_J1", stan::model::index_uni(sym1__));
          current_statement__ = 60;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 61;
      context__.validate_dims("data initialization", "T_post", "int",
        std::vector<size_t>{});
      T_post = std::numeric_limits<int>::min();
      current_statement__ = 61;
      T_post = context__.vals_i("T_post")[(1 - 1)];
      current_statement__ = 61;
      stan::math::check_greater_or_equal(function__, "T_post", T_post, 1);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("Y0_post", "T_post", T_post);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("Y0_post", "J", J);
      current_statement__ = 64;
      context__.validate_dims("data initialization", "Y0_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post),
          static_cast<size_t>(J)});
      Y0_post_data__ = Eigen::Matrix<double,-1,-1>::Constant(T_post, J,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y0_post)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y0_post_data__.data(),
        T_post, J);
      {
        std::vector<local_scalar_t__> Y0_post_flat__;
        current_statement__ = 64;
        Y0_post_flat__ = context__.vals_r("Y0_post");
        current_statement__ = 64;
        pos__ = 1;
        current_statement__ = 64;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 64;
          for (int sym2__ = 1; sym2__ <= T_post; ++sym2__) {
            current_statement__ = 64;
            stan::model::assign(Y0_post, Y0_post_flat__[(pos__ - 1)],
              "assigning variable Y0_post", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 64;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 65;
      stan::math::validate_non_negative_index("Y1_post", "T_post", T_post);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "Y1_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post)});
      Y1_post_data__ = Eigen::Matrix<double,-1,1>::Constant(T_post,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y1_post)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y1_post_data__.data(), T_post);
      {
        std::vector<local_scalar_t__> Y1_post_flat__;
        current_statement__ = 66;
        Y1_post_flat__ = context__.vals_r("Y1_post");
        current_statement__ = 66;
        pos__ = 1;
        current_statement__ = 66;
        for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
          current_statement__ = 66;
          stan::model::assign(Y1_post, Y1_post_flat__[(pos__ - 1)],
            "assigning variable Y1_post", stan::model::index_uni(sym1__));
          current_statement__ = 66;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 67;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 69;
      I_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&I_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(I_J_data__.data(),
        J, J);
      current_statement__ = 69;
      stan::model::assign(I_J,
        stan::math::diag_matrix(stan::math::rep_vector(1.0, J)),
        "assigning variable I_J");
      current_statement__ = 70;
      stan::math::validate_non_negative_index("I_full", "J + 1", (J + 1));
      current_statement__ = 71;
      stan::math::validate_non_negative_index("I_full", "J + 1", (J + 1));
      current_statement__ = 72;
      I_full_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), (J + 1),
                        std::numeric_limits<double>::quiet_NaN());
      new (&I_full)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(I_full_data__.data(), (J +
        1), (J + 1));
      current_statement__ = 72;
      stan::model::assign(I_full,
        stan::math::diag_matrix(stan::math::rep_vector(1.0, (J + 1))),
        "assigning variable I_full");
      current_statement__ = 73;
      stan::math::validate_non_negative_index("X0_std", "K_pred", K_pred);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("X0_std", "J", J);
      current_statement__ = 75;
      X0_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(K_pred, J,
                        std::numeric_limits<double>::quiet_NaN());
      new (&X0_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X0_std_data__.data(), K_pred,
        J);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("X1_std", "K_pred", K_pred);
      current_statement__ = 77;
      X1_std_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                        std::numeric_limits<double>::quiet_NaN());
      new (&X1_std)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(X1_std_data__.data(), K_pred);
      current_statement__ = 82;
      for (int k = 1; k <= K_pred; ++k) {
        double sd_k = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 78;
        sd_k = stan::math::sd(
                 stan::model::rvalue(X0, "X0", stan::model::index_uni(k),
                   stan::model::index_omni()));
        current_statement__ = 79;
        stan::model::assign(X0_std,
          stan::math::divide(
            stan::model::rvalue(X0, "X0", stan::model::index_uni(k),
              stan::model::index_omni()), sd_k), "assigning variable X0_std",
          stan::model::index_uni(k), stan::model::index_omni());
        current_statement__ = 80;
        stan::model::assign(X1_std,
          (stan::model::rvalue(X1, "X1", stan::model::index_uni(k)) / sd_k),
          "assigning variable X1_std", stan::model::index_uni(k));
      }
      current_statement__ = 83;
      stan::math::validate_non_negative_index("X_full_std", "J + 1", (J + 1));
      current_statement__ = 84;
      stan::math::validate_non_negative_index("X_full_std", "K_pred", K_pred);
      current_statement__ = 85;
      X_full_std_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1),
                            K_pred, std::numeric_limits<double>::quiet_NaN());
      new (&X_full_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_full_std_data__.data(), (J
        + 1), K_pred);
      current_statement__ = 89;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 86;
        stan::model::assign(X_full_std,
          stan::math::to_vector(
            stan::model::rvalue(X0_std, "X0_std", stan::model::index_uni(k),
              stan::model::index_omni())), "assigning variable X_full_std",
          stan::model::index_min_max(1, J), stan::model::index_uni(k));
        current_statement__ = 87;
        stan::model::assign(X_full_std,
          stan::model::rvalue(X1_std, "X1_std", stan::model::index_uni(k)),
          "assigning variable X_full_std", stan::model::index_uni((J + 1)),
          stan::model::index_uni(k));
      }
      current_statement__ = 90;
      stan::math::validate_non_negative_index("beta", "K_pred", K_pred);
      current_statement__ = 91;
      mu_1dim__ = std::numeric_limits<int>::min();
      current_statement__ = 91;
      mu_1dim__ = (J + 1);
      current_statement__ = 91;
      stan::math::validate_non_negative_index("mu", "J + 1", mu_1dim__);
      current_statement__ = 92;
      stan::math::validate_positive_index("w", "J", J);
      current_statement__ = 93;
      stan::math::validate_positive_index("gamma_imp", "K_pred", K_pred);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("s", "J", J);
      current_statement__ = 95;
      stan::math::validate_non_negative_index("Omega", "K_pred", K_pred);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("tau_nasc", "T_post", T_post);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + K_pred + mu_1dim__ + 1 + (J - 1) + (K_pred - 1) + 1
      + 1;
  }
  inline std::string model_name() const final {
    return "model_nasc_SAR";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_nasc_SAR_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      mu = in__.template read<
             Eigen::Matrix<local_scalar_t__,-1,1>>(mu_1dim__);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sar = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_imp =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 6;
      gamma_imp = in__.template read_constrain_simplex<
                    Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                    K_pred);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sc = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 8;
      lambda = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> s =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(s,
        stan::math::multiply(rho,
          stan::math::mdivide_left(
            stan::math::subtract(I_J, stan::math::multiply(rho, W_J)), w_J1)),
        "assigning variable s");
      Eigen::Matrix<local_scalar_t__,-1,1> Omega =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 15;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 13;
        stan::model::assign(Omega, (sigma_sc /
          stan::model::rvalue(gamma_imp, "gamma_imp",
            stan::model::index_uni(k))), "assigning variable Omega",
          stan::model::index_uni(k));
      }
      {
        current_statement__ = 20;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(rho, -1, 1));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, 0, 10));
        current_statement__ = 22;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_sar, 0, 5));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 5));
        current_statement__ = 24;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma_sc, 0, 5));
        current_statement__ = 25;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(lambda, 0, 10));
        current_statement__ = 26;
        lp_accum__.add(stan::math::dirichlet_lpdf<propto__>(gamma_imp, vs));
        {
          current_statement__ = 27;
          stan::math::validate_non_negative_index("A", "J + 1", (J + 1));
          current_statement__ = 28;
          stan::math::validate_non_negative_index("A", "J + 1", (J + 1));
          Eigen::Matrix<local_scalar_t__,-1,-1> A =
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant((J + 1), (J + 1),
              DUMMY_VAR__);
          current_statement__ = 29;
          stan::model::assign(A,
            stan::math::subtract(I_full, stan::math::multiply(rho, W)),
            "assigning variable A");
          local_scalar_t__ log_det_A = DUMMY_VAR__;
          current_statement__ = 30;
          log_det_A = stan::math::log_determinant(A);
          current_statement__ = 31;
          stan::math::validate_non_negative_index("sar_mean", "J + 1", (J +
            1));
          Eigen::Matrix<local_scalar_t__,-1,1> sar_mean =
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant((J + 1),
              DUMMY_VAR__);
          current_statement__ = 32;
          stan::model::assign(sar_mean,
            stan::math::add(mu, stan::math::multiply(X_full_std, beta)),
            "assigning variable sar_mean");
          current_statement__ = 36;
          for (int t = 1; t <= T0; ++t) {
            current_statement__ = 33;
            lp_accum__.add(log_det_A);
            current_statement__ = 34;
            lp_accum__.add(stan::math::normal_lpdf<false>(
                             stan::math::multiply(A,
                               stan::model::rvalue(Y_panel, "Y_panel",
                                 stan::model::index_omni(),
                                 stan::model::index_uni(t))), sar_mean,
                             sigma_sar));
          }
        }
        current_statement__ = 38;
        lp_accum__.add((-lambda *
          stan::math::dot_product(w, stan::math::fabs(s))));
        current_statement__ = 39;
        lp_accum__.add(stan::math::normal_lpdf<false>(X1_std,
                         stan::math::multiply(X0_std, w), Omega));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_nasc_SAR_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<double,-1,1> mu =
        Eigen::Matrix<double,-1,1>::Constant(mu_1dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      mu = in__.template read<
             Eigen::Matrix<local_scalar_t__,-1,1>>(mu_1dim__);
      double sigma_sar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_sar = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> w =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      Eigen::Matrix<double,-1,1> gamma_imp =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      gamma_imp = in__.template read_constrain_simplex<
                    Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__,
                    K_pred);
      double sigma_sc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      sigma_sc = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      double lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      lambda = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> s =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> Omega =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(rho);
      out__.write(beta);
      out__.write(mu);
      out__.write(sigma_sar);
      out__.write(w);
      out__.write(gamma_imp);
      out__.write(sigma_sc);
      out__.write(lambda);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 9;
      stan::model::assign(s,
        stan::math::multiply(rho,
          stan::math::mdivide_left(
            stan::math::subtract(I_J, stan::math::multiply(rho, W_J)), w_J1)),
        "assigning variable s");
      current_statement__ = 15;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 13;
        stan::model::assign(Omega, (sigma_sc /
          stan::model::rvalue(gamma_imp, "gamma_imp",
            stan::model::index_uni(k))), "assigning variable Omega",
          stan::model::index_uni(k));
      }
      if (emit_transformed_parameters__) {
        out__.write(s);
        out__.write(Omega);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> tau_nasc =
        Eigen::Matrix<double,-1,1>::Constant(T_post,
          std::numeric_limits<double>::quiet_NaN());
      double bias_correction = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      bias_correction = (1.0 / (1.0 - stan::math::dot_product(w, s)));
      current_statement__ = 19;
      for (int t = 1; t <= T_post; ++t) {
        double raw_effect = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 16;
        raw_effect = (stan::model::rvalue(Y1_post, "Y1_post",
                        stan::model::index_uni(t))
          -
          stan::math::dot_product(
            stan::model::rvalue(Y0_post, "Y0_post",
              stan::model::index_uni(t), stan::model::index_omni()), w));
        current_statement__ = 17;
        stan::model::assign(tau_nasc, (raw_effect * bias_correction),
          "assigning variable tau_nasc", stan::model::index_uni(t));
      }
      out__.write(tau_nasc);
      out__.write(bias_correction);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_1dim__,
          DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(mu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(mu_1dim__),
        "assigning variable mu");
      out__.write(mu);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sar = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sar);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(w,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable w");
      out__.write_free_simplex(w);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_imp =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(gamma_imp,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable gamma_imp");
      out__.write_free_simplex(gamma_imp);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sc = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sc);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 8;
      lambda = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{static_cast<size_t>(mu_1dim__)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_sar",
        "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "gamma_imp",
        "double", std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sigma_sc",
        "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(mu_1dim__,
          DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> mu_flat__;
        current_statement__ = 3;
        mu_flat__ = context__.vals_r("mu");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= mu_1dim__; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(mu, mu_flat__[(pos__ - 1)],
            "assigning variable mu", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(mu);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sar = context__.vals_r("sigma_sar")[(1 - 1)];
      out__.write_free_lb(0, sigma_sar);
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 5;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 5;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 5;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(w);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_imp =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gamma_imp_flat__;
        current_statement__ = 6;
        gamma_imp_flat__ = context__.vals_r("gamma_imp");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 6;
          stan::model::assign(gamma_imp, gamma_imp_flat__[(pos__ - 1)],
            "assigning variable gamma_imp", stan::model::index_uni(sym1__));
          current_statement__ = 6;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(gamma_imp);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sc = context__.vals_r("sigma_sc")[(1 - 1)];
      out__.write_free_lb(0, sigma_sc);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 8;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"rho", "beta", "mu", "sigma_sar", "w",
                "gamma_imp", "sigma_sc", "lambda"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"s", "Omega"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"tau_nasc", "bias_correction"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{static_cast<size_t>(mu_1dim__)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(J)},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(J)},
             std::vector<size_t>{static_cast<size_t>(K_pred)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T_post)},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= mu_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sar");
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma_imp" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sc");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "s" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "Omega" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "tau_nasc" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "bias_correction");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= mu_1dim__; ++sym1__) {
      param_names__.emplace_back(std::string() + "mu" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sar");
    for (int sym1__ = 1; sym1__ <= (J - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= (K_pred - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma_imp" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sc");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
        param_names__.emplace_back(std::string() + "s" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "Omega" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "tau_nasc" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "bias_correction");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(mu_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"gamma_imp\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Omega\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau_nasc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(mu_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((J -1)) + "},\"block\":\"parameters\"},{\"name\":\"gamma_imp\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((K_pred -1)) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"s\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Omega\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"transformed_parameters\"},{\"name\":\"tau_nasc\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((1 + K_pred) + mu_1dim__) + 1) + J) +
      K_pred) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((J +
      K_pred));
    const size_t num_gen_quantities = emit_generated_quantities * ((T_post +
      1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((1 + K_pred) + mu_1dim__) + 1) + J) +
      K_pred) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((J +
      K_pred));
    const size_t num_gen_quantities = emit_generated_quantities * ((T_post +
      1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_nasc_SAR_namespace::model_nasc_SAR;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_nasc_SAR_namespace::profiles__;
}
#endif
#endif
