// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stan_1_SDM_NASC_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 120> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 94, column 2 to column 30)",
  " (in 'string', line 95, column 2 to column 22)",
  " (in 'string', line 96, column 2 to column 23)",
  " (in 'string', line 97, column 2 to column 26)",
  " (in 'string', line 117, column 2 to column 21)",
  " (in 'string', line 101, column 2 to column 27)",
  " (in 'string', line 102, column 2 to column 27)",
  " (in 'string', line 103, column 2 to column 27)",
  " (in 'string', line 105, column 2 to column 46)",
  " (in 'string', line 106, column 2 to column 27)",
  " (in 'string', line 109, column 9 to column 10)",
  " (in 'string', line 109, column 12 to column 14)",
  " (in 'string', line 109, column 2 to column 40)",
  " (in 'string', line 111, column 4 to column 36)",
  " (in 'string', line 112, column 4 to column 37)",
  " (in 'string', line 110, column 22 to line 113, column 3)",
  " (in 'string', line 110, column 2 to line 113, column 3)",
  " (in 'string', line 114, column 2 to column 68)",
  " (in 'string', line 18, column 2 to column 22)",
  " (in 'string', line 19, column 2 to column 17)",
  " (in 'string', line 20, column 2 to column 18)",
  " (in 'string', line 21, column 8 to column 10)",
  " (in 'string', line 21, column 19 to column 25)",
  " (in 'string', line 21, column 2 to column 30)",
  " (in 'string', line 22, column 8 to column 10)",
  " (in 'string', line 22, column 19 to column 25)",
  " (in 'string', line 22, column 27 to column 28)",
  " (in 'string', line 22, column 2 to column 33)",
  " (in 'string', line 23, column 9 to column 14)",
  " (in 'string', line 23, column 16 to column 18)",
  " (in 'string', line 23, column 2 to column 28)",
  " (in 'string', line 24, column 9 to column 14)",
  " (in 'string', line 24, column 16 to column 21)",
  " (in 'string', line 24, column 2 to column 25)",
  " (in 'string', line 25, column 9 to column 14)",
  " (in 'string', line 25, column 2 to column 25)",
  " (in 'string', line 28, column 2 to column 16)",
  " (in 'string', line 30, column 2 to column 41)",
  " (in 'string', line 31, column 2 to column 39)",
  " (in 'string', line 32, column 9 to column 10)",
  " (in 'string', line 32, column 12 to column 14)",
  " (in 'string', line 32, column 2 to column 51)",
  " (in 'string', line 33, column 9 to column 10)",
  " (in 'string', line 33, column 12 to column 14)",
  " (in 'string', line 33, column 2 to column 35)",
  " (in 'string', line 35, column 8 to column 14)",
  " (in 'string', line 35, column 23 to column 24)",
  " (in 'string', line 35, column 26 to column 28)",
  " (in 'string', line 35, column 2 to column 41)",
  " (in 'string', line 37, column 11 to column 12)",
  " (in 'string', line 37, column 14 to column 16)",
  " (in 'string', line 37, column 4 to column 21)",
  " (in 'string', line 40, column 8 to column 31)",
  " (in 'string', line 39, column 6 to line 40, column 31)",
  " (in 'string', line 41, column 6 to column 26)",
  " (in 'string', line 38, column 20 to line 42, column 5)",
  " (in 'string', line 38, column 4 to line 42, column 5)",
  " (in 'string', line 43, column 4 to column 33)",
  " (in 'string', line 44, column 4 to column 31)",
  " (in 'string', line 45, column 4 to column 70)",
  " (in 'string', line 36, column 22 to line 46, column 3)",
  " (in 'string', line 36, column 2 to line 46, column 3)",
  " (in 'string', line 49, column 8 to column 14)",
  " (in 'string', line 49, column 23 to column 24)",
  " (in 'string', line 49, column 26 to column 28)",
  " (in 'string', line 49, column 2 to column 42)",
  " (in 'string', line 51, column 4 to column 39)",
  " (in 'string', line 50, column 2 to line 51, column 39)",
  " (in 'string', line 53, column 9 to column 10)",
  " (in 'string', line 53, column 12 to column 14)",
  " (in 'string', line 53, column 2 to column 25)",
  " (in 'string', line 54, column 9 to column 10)",
  " (in 'string', line 54, column 12 to column 14)",
  " (in 'string', line 54, column 2 to column 26)",
  " (in 'string', line 55, column 8 to column 14)",
  " (in 'string', line 55, column 23 to column 24)",
  " (in 'string', line 55, column 26 to column 28)",
  " (in 'string', line 55, column 2 to column 39)",
  " (in 'string', line 56, column 8 to column 14)",
  " (in 'string', line 56, column 23 to column 24)",
  " (in 'string', line 56, column 26 to column 28)",
  " (in 'string', line 56, column 2 to column 40)",
  " (in 'string', line 59, column 11 to column 12)",
  " (in 'string', line 59, column 4 to column 67)",
  " (in 'string', line 60, column 15 to column 17)",
  " (in 'string', line 60, column 4 to column 69)",
  " (in 'string', line 61, column 4 to column 57)",
  " (in 'string', line 64, column 8 to column 81)",
  " (in 'string', line 63, column 6 to line 64, column 81)",
  " (in 'string', line 62, column 4 to line 64, column 81)",
  " (in 'string', line 66, column 11 to column 12)",
  " (in 'string', line 66, column 4 to column 68)",
  " (in 'string', line 67, column 15 to column 17)",
  " (in 'string', line 67, column 4 to column 70)",
  " (in 'string', line 68, column 4 to column 58)",
  " (in 'string', line 71, column 8 to column 86)",
  " (in 'string', line 70, column 6 to line 71, column 86)",
  " (in 'string', line 69, column 4 to line 71, column 86)",
  " (in 'string', line 75, column 13 to column 14)",
  " (in 'string', line 75, column 6 to column 76)",
  " (in 'string', line 76, column 17 to column 19)",
  " (in 'string', line 76, column 6 to column 78)",
  " (in 'string', line 77, column 6 to column 66)",
  " (in 'string', line 80, column 10 to line 81, column 74)",
  " (in 'string', line 79, column 8 to line 81, column 74)",
  " (in 'string', line 78, column 6 to line 81, column 74)",
  " (in 'string', line 83, column 13 to column 14)",
  " (in 'string', line 83, column 6 to column 78)",
  " (in 'string', line 84, column 17 to column 19)",
  " (in 'string', line 84, column 6 to column 80)",
  " (in 'string', line 85, column 6 to column 68)",
  " (in 'string', line 88, column 10 to line 89, column 78)",
  " (in 'string', line 87, column 8 to line 89, column 78)",
  " (in 'string', line 86, column 6 to line 89, column 78)",
  " (in 'string', line 73, column 24 to line 90, column 5)",
  " (in 'string', line 73, column 4 to line 90, column 5)",
  " (in 'string', line 57, column 2 to line 91, column 3)",
  " (in 'string', line 95, column 9 to column 15)",
  " (in 'string', line 96, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_stan_1_SDM_NASC final : public model_base_crtp<model_stan_1_SDM_NASC> {
private:
  int K_pred;
  int J;
  int T0;
  std::vector<Eigen::Matrix<double,-1,1>> X1;
  std::vector<Eigen::Matrix<double,-1,-1>> X0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_data__;
  Eigen::Matrix<double,-1,1> lambda_W_data__;
  int N;
  double mean_y;
  double sd_y;
  Eigen::Matrix<double,-1,-1> Y_std_data__;
  Eigen::Matrix<double,-1,-1> WY_std_data__;
  std::vector<Eigen::Matrix<double,-1,-1>> X_full_std;
  std::vector<Eigen::Matrix<double,-1,-1>> WX_full_std;
  Eigen::Matrix<double,-1,-1> Y_within_data__;
  Eigen::Matrix<double,-1,-1> WY_within_data__;
  std::vector<Eigen::Matrix<double,-1,-1>> X_within;
  std::vector<Eigen::Matrix<double,-1,-1>> WX_within;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> lambda_W{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> WY_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_within{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> WY_within{nullptr, 0, 0};
public:
  ~model_stan_1_SDM_NASC() {}
  model_stan_1_SDM_NASC(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::model_stan_1_SDM_NASC";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 19;
      context__.validate_dims("data initialization", "K_pred", "int",
        std::vector<size_t>{});
      K_pred = std::numeric_limits<int>::min();
      current_statement__ = 19;
      K_pred = context__.vals_i("K_pred")[(1 - 1)];
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "K_pred", K_pred, 0);
      current_statement__ = 20;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 20;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 20;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 21;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 21;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 21;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 22;
      stan::math::validate_non_negative_index("X1", "T0", T0);
      current_statement__ = 23;
      stan::math::validate_non_negative_index("X1", "K_pred", K_pred);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "X1", "double",
        std::vector<size_t>{static_cast<size_t>(T0),
          static_cast<size_t>(K_pred)});
      X1 = std::vector<Eigen::Matrix<double,-1,1>>(T0,
             Eigen::Matrix<double,-1,1>::Constant(K_pred,
               std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X1_flat__;
        current_statement__ = 24;
        X1_flat__ = context__.vals_r("X1");
        current_statement__ = 24;
        pos__ = 1;
        current_statement__ = 24;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 24;
          for (int sym2__ = 1; sym2__ <= T0; ++sym2__) {
            current_statement__ = 24;
            stan::model::assign(X1, X1_flat__[(pos__ - 1)],
              "assigning variable X1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 24;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 25;
      stan::math::validate_non_negative_index("X0", "T0", T0);
      current_statement__ = 26;
      stan::math::validate_non_negative_index("X0", "K_pred", K_pred);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("X0", "J", J);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "X0", "double",
        std::vector<size_t>{static_cast<size_t>(T0),
          static_cast<size_t>(K_pred), static_cast<size_t>(J)});
      X0 = std::vector<Eigen::Matrix<double,-1,-1>>(T0,
             Eigen::Matrix<double,-1,-1>::Constant(K_pred, J,
               std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X0_flat__;
        current_statement__ = 28;
        X0_flat__ = context__.vals_r("X0");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 28;
          for (int sym2__ = 1; sym2__ <= K_pred; ++sym2__) {
            current_statement__ = 28;
            for (int sym3__ = 1; sym3__ <= T0; ++sym3__) {
              current_statement__ = 28;
              stan::model::assign(X0, X0_flat__[(pos__ - 1)],
                "assigning variable X0", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 28;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 29;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 30;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 31;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 31;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 31;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 31;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 33;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 34;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>((J + 1))});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), (J + 1),
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), (J +
        1), (J + 1));
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 34;
        W_flat__ = context__.vals_r("W");
        current_statement__ = 34;
        pos__ = 1;
        current_statement__ = 34;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 34;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 34;
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 34;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 35;
      stan::math::validate_non_negative_index("lambda_W", "J + 1", (J + 1));
      current_statement__ = 36;
      context__.validate_dims("data initialization", "lambda_W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1))});
      lambda_W_data__ = Eigen::Matrix<double,-1,1>::Constant((J + 1),
                          std::numeric_limits<double>::quiet_NaN());
      new (&lambda_W)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(lambda_W_data__.data(), (J +
        1));
      {
        std::vector<local_scalar_t__> lambda_W_flat__;
        current_statement__ = 36;
        lambda_W_flat__ = context__.vals_r("lambda_W");
        current_statement__ = 36;
        pos__ = 1;
        current_statement__ = 36;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 36;
          stan::model::assign(lambda_W, lambda_W_flat__[(pos__ - 1)],
            "assigning variable lambda_W", stan::model::index_uni(sym1__));
          current_statement__ = 36;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 37;
      N = std::numeric_limits<int>::min();
      current_statement__ = 37;
      N = (J + 1);
      current_statement__ = 38;
      mean_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 38;
      mean_y = stan::math::mean(stan::math::to_vector(Y_panel));
      current_statement__ = 39;
      sd_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      sd_y = stan::math::sd(stan::math::to_vector(Y_panel));
      current_statement__ = 40;
      stan::math::validate_non_negative_index("Y_std", "N", N);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("Y_std", "T0", T0);
      current_statement__ = 42;
      Y_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                       std::numeric_limits<double>::quiet_NaN());
      new (&Y_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_std_data__.data(), N, T0);
      current_statement__ = 42;
      stan::model::assign(Y_std,
        stan::math::divide(stan::math::subtract(Y_panel, mean_y), sd_y),
        "assigning variable Y_std");
      current_statement__ = 43;
      stan::math::validate_non_negative_index("WY_std", "N", N);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("WY_std", "T0", T0);
      current_statement__ = 45;
      WY_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                        std::numeric_limits<double>::quiet_NaN());
      new (&WY_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(WY_std_data__.data(), N, T0);
      current_statement__ = 45;
      stan::model::assign(WY_std, stan::math::multiply(W, Y_std),
        "assigning variable WY_std");
      current_statement__ = 46;
      stan::math::validate_non_negative_index("X_full_std", "K_pred", K_pred);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("X_full_std", "N", N);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("X_full_std", "T0", T0);
      current_statement__ = 49;
      X_full_std = std::vector<Eigen::Matrix<double,-1,-1>>(K_pred,
                     Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                       std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 62;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 50;
        stan::math::validate_non_negative_index("Xk", "N", N);
        current_statement__ = 51;
        stan::math::validate_non_negative_index("Xk", "T0", T0);
        Eigen::Matrix<double,-1,-1> Xk =
          Eigen::Matrix<double,-1,-1>::Constant(N, T0,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 57;
        for (int t = 1; t <= T0; ++t) {
          current_statement__ = 54;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 53;
            stan::model::assign(Xk,
              stan::model::rvalue(X0, "X0", stan::model::index_uni(t),
                stan::model::index_uni(k), stan::model::index_uni(j)),
              "assigning variable Xk", stan::model::index_uni(j),
              stan::model::index_uni(t));
          }
          current_statement__ = 55;
          stan::model::assign(Xk,
            stan::model::rvalue(X1, "X1", stan::model::index_uni(t),
              stan::model::index_uni(k)), "assigning variable Xk",
            stan::model::index_uni(N), stan::model::index_uni(t));
        }
        double m = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 58;
        m = stan::math::mean(stan::math::to_vector(Xk));
        double s = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 59;
        s = stan::math::sd(stan::math::to_vector(Xk));
        current_statement__ = 60;
        stan::model::assign(X_full_std,
          (stan::math::logical_gt(s, 1e-12) ? stan::math::eval(
                                                stan::math::divide(
                                                  stan::math::subtract(Xk, m),
                                                  s)) : stan::math::eval(
                                                          stan::math::rep_matrix(
                                                            0.0, N, T0))),
          "assigning variable X_full_std", stan::model::index_uni(k));
      }
      current_statement__ = 63;
      stan::math::validate_non_negative_index("WX_full_std", "K_pred", K_pred);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("WX_full_std", "N", N);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("WX_full_std", "T0", T0);
      current_statement__ = 66;
      WX_full_std = std::vector<Eigen::Matrix<double,-1,-1>>(K_pred,
                      Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                        std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 68;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 67;
        stan::model::assign(WX_full_std,
          stan::math::multiply(W,
            stan::model::rvalue(X_full_std, "X_full_std",
              stan::model::index_uni(k))), "assigning variable WX_full_std",
          stan::model::index_uni(k));
      }
      current_statement__ = 69;
      stan::math::validate_non_negative_index("Y_within", "N", N);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("Y_within", "T0", T0);
      current_statement__ = 71;
      Y_within_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                          std::numeric_limits<double>::quiet_NaN());
      new (&Y_within)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_within_data__.data(), N,
        T0);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("WY_within", "N", N);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("WY_within", "T0", T0);
      current_statement__ = 74;
      WY_within_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                           std::numeric_limits<double>::quiet_NaN());
      new (&WY_within)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(WY_within_data__.data(), N,
        T0);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("X_within", "K_pred", K_pred);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("X_within", "N", N);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("X_within", "T0", T0);
      current_statement__ = 78;
      X_within = std::vector<Eigen::Matrix<double,-1,-1>>(K_pred,
                   Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                     std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 79;
      stan::math::validate_non_negative_index("WX_within", "K_pred", K_pred);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("WX_within", "N", N);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("WX_within", "T0", T0);
      current_statement__ = 82;
      WX_within = std::vector<Eigen::Matrix<double,-1,-1>>(K_pred,
                    Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                      std::numeric_limits<double>::quiet_NaN()));
      {
        current_statement__ = 83;
        stan::math::validate_non_negative_index("row_means_Y", "N", N);
        Eigen::Matrix<double,-1,1> row_means_Y =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 84;
        stan::model::assign(row_means_Y,
          stan::math::multiply(Y_std, stan::math::rep_vector((1.0 / T0), T0)),
          "assigning variable row_means_Y");
        current_statement__ = 85;
        stan::math::validate_non_negative_index("col_means_Y", "T0", T0);
        Eigen::Matrix<double,1,-1> col_means_Y =
          Eigen::Matrix<double,1,-1>::Constant(T0,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 86;
        stan::model::assign(col_means_Y,
          stan::math::multiply(stan::math::rep_row_vector((1.0 / N), N),
            Y_std), "assigning variable col_means_Y");
        double grand_Y = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 87;
        grand_Y = stan::math::mean(stan::math::to_vector(Y_std));
        current_statement__ = 90;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 89;
          for (int t = 1; t <= T0; ++t) {
            current_statement__ = 88;
            stan::model::assign(Y_within,
              (((stan::model::rvalue(Y_std, "Y_std",
                   stan::model::index_uni(i), stan::model::index_uni(t)) -
              stan::model::rvalue(row_means_Y, "row_means_Y",
                stan::model::index_uni(i))) -
              stan::model::rvalue(col_means_Y, "col_means_Y",
                stan::model::index_uni(t))) + grand_Y),
              "assigning variable Y_within", stan::model::index_uni(i),
              stan::model::index_uni(t));
          }
        }
        current_statement__ = 91;
        stan::math::validate_non_negative_index("row_means_WY", "N", N);
        Eigen::Matrix<double,-1,1> row_means_WY =
          Eigen::Matrix<double,-1,1>::Constant(N,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 92;
        stan::model::assign(row_means_WY,
          stan::math::multiply(WY_std, stan::math::rep_vector((1.0 / T0), T0)),
          "assigning variable row_means_WY");
        current_statement__ = 93;
        stan::math::validate_non_negative_index("col_means_WY", "T0", T0);
        Eigen::Matrix<double,1,-1> col_means_WY =
          Eigen::Matrix<double,1,-1>::Constant(T0,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 94;
        stan::model::assign(col_means_WY,
          stan::math::multiply(stan::math::rep_row_vector((1.0 / N), N),
            WY_std), "assigning variable col_means_WY");
        double grand_WY = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 95;
        grand_WY = stan::math::mean(stan::math::to_vector(WY_std));
        current_statement__ = 98;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 97;
          for (int t = 1; t <= T0; ++t) {
            current_statement__ = 96;
            stan::model::assign(WY_within,
              (((stan::model::rvalue(WY_std, "WY_std",
                   stan::model::index_uni(i), stan::model::index_uni(t)) -
              stan::model::rvalue(row_means_WY, "row_means_WY",
                stan::model::index_uni(i))) -
              stan::model::rvalue(col_means_WY, "col_means_WY",
                stan::model::index_uni(t))) + grand_WY),
              "assigning variable WY_within", stan::model::index_uni(i),
              stan::model::index_uni(t));
          }
        }
        current_statement__ = 116;
        for (int k = 1; k <= K_pred; ++k) {
          current_statement__ = 99;
          stan::math::validate_non_negative_index("row_means_X", "N", N);
          Eigen::Matrix<double,-1,1> row_means_X =
            Eigen::Matrix<double,-1,1>::Constant(N,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 100;
          stan::model::assign(row_means_X,
            stan::math::multiply(
              stan::model::rvalue(X_full_std, "X_full_std",
                stan::model::index_uni(k)),
              stan::math::rep_vector((1.0 / T0), T0)),
            "assigning variable row_means_X");
          current_statement__ = 101;
          stan::math::validate_non_negative_index("col_means_X", "T0", T0);
          Eigen::Matrix<double,1,-1> col_means_X =
            Eigen::Matrix<double,1,-1>::Constant(T0,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 102;
          stan::model::assign(col_means_X,
            stan::math::multiply(stan::math::rep_row_vector((1.0 / N), N),
              stan::model::rvalue(X_full_std, "X_full_std",
                stan::model::index_uni(k))), "assigning variable col_means_X");
          double grand_X = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 103;
          grand_X = stan::math::mean(
                      stan::math::to_vector(
                        stan::model::rvalue(X_full_std, "X_full_std",
                          stan::model::index_uni(k))));
          current_statement__ = 106;
          for (int i = 1; i <= N; ++i) {
            current_statement__ = 105;
            for (int t = 1; t <= T0; ++t) {
              current_statement__ = 104;
              stan::model::assign(X_within,
                (((stan::model::rvalue(X_full_std, "X_full_std",
                     stan::model::index_uni(k), stan::model::index_uni(i),
                     stan::model::index_uni(t)) -
                stan::model::rvalue(row_means_X, "row_means_X",
                  stan::model::index_uni(i))) -
                stan::model::rvalue(col_means_X, "col_means_X",
                  stan::model::index_uni(t))) + grand_X),
                "assigning variable X_within", stan::model::index_uni(k),
                stan::model::index_uni(i), stan::model::index_uni(t));
            }
          }
          current_statement__ = 107;
          stan::math::validate_non_negative_index("row_means_WX", "N", N);
          Eigen::Matrix<double,-1,1> row_means_WX =
            Eigen::Matrix<double,-1,1>::Constant(N,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 108;
          stan::model::assign(row_means_WX,
            stan::math::multiply(
              stan::model::rvalue(WX_full_std, "WX_full_std",
                stan::model::index_uni(k)),
              stan::math::rep_vector((1.0 / T0), T0)),
            "assigning variable row_means_WX");
          current_statement__ = 109;
          stan::math::validate_non_negative_index("col_means_WX", "T0", T0);
          Eigen::Matrix<double,1,-1> col_means_WX =
            Eigen::Matrix<double,1,-1>::Constant(T0,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 110;
          stan::model::assign(col_means_WX,
            stan::math::multiply(stan::math::rep_row_vector((1.0 / N), N),
              stan::model::rvalue(WX_full_std, "WX_full_std",
                stan::model::index_uni(k))),
            "assigning variable col_means_WX");
          double grand_WX = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 111;
          grand_WX = stan::math::mean(
                       stan::math::to_vector(
                         stan::model::rvalue(WX_full_std, "WX_full_std",
                           stan::model::index_uni(k))));
          current_statement__ = 114;
          for (int i = 1; i <= N; ++i) {
            current_statement__ = 113;
            for (int t = 1; t <= T0; ++t) {
              current_statement__ = 112;
              stan::model::assign(WX_within,
                (((stan::model::rvalue(WX_full_std, "WX_full_std",
                     stan::model::index_uni(k), stan::model::index_uni(i),
                     stan::model::index_uni(t)) -
                stan::model::rvalue(row_means_WX, "row_means_WX",
                  stan::model::index_uni(i))) -
                stan::model::rvalue(col_means_WX, "col_means_WX",
                  stan::model::index_uni(t))) + grand_WX),
                "assigning variable WX_within", stan::model::index_uni(k),
                stan::model::index_uni(i), stan::model::index_uni(t));
            }
          }
        }
      }
      current_statement__ = 118;
      stan::math::validate_non_negative_index("beta", "K_pred", K_pred);
      current_statement__ = 119;
      stan::math::validate_non_negative_index("theta", "K_pred", K_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + K_pred + K_pred + 1;
  }
  inline std::string model_name() const final {
    return "model_stan_1_SDM_NASC";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 3;
      theta = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      {
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_sdm, 0, 1));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(theta, 0, 1));
        local_scalar_t__ log_det_A = DUMMY_VAR__;
        current_statement__ = 9;
        log_det_A = stan::math::sum(
                      stan::math::log1m(stan::math::multiply(rho, lambda_W)));
        current_statement__ = 10;
        lp_accum__.add((T0 * log_det_A));
        current_statement__ = 11;
        stan::math::validate_non_negative_index("mu_lp", "N", N);
        current_statement__ = 12;
        stan::math::validate_non_negative_index("mu_lp", "T0", T0);
        Eigen::Matrix<local_scalar_t__,-1,-1> mu_lp =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, T0, DUMMY_VAR__);
        current_statement__ = 13;
        stan::model::assign(mu_lp, stan::math::multiply(rho, WY_within),
          "assigning variable mu_lp");
        current_statement__ = 17;
        for (int k = 1; k <= K_pred; ++k) {
          current_statement__ = 14;
          stan::model::assign(mu_lp,
            stan::math::add(stan::model::deep_copy(mu_lp),
              stan::math::multiply(
                stan::model::rvalue(beta, "beta", stan::model::index_uni(k)),
                stan::model::rvalue(X_within, "X_within",
                  stan::model::index_uni(k)))), "assigning variable mu_lp");
          current_statement__ = 15;
          stan::model::assign(mu_lp,
            stan::math::add(stan::model::deep_copy(mu_lp),
              stan::math::multiply(
                stan::model::rvalue(theta, "theta", stan::model::index_uni(k)),
                stan::model::rvalue(WX_within, "WX_within",
                  stan::model::index_uni(k)))), "assigning variable mu_lp");
        }
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<false>(
                         stan::math::to_vector(
                           stan::math::subtract(Y_within, mu_lp)), 0,
                         sigma_sdm));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stan_1_SDM_NASC_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<double,-1,1> theta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      theta = in__.template read<
                Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      double sigma_sdm = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      sigma_sdm = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      out__.write(rho);
      out__.write(beta);
      out__.write(theta);
      out__.write(sigma_sdm);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double rho_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      rho_out = rho;
      out__.write(rho_out);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(theta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable theta");
      out__.write(theta);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sdm);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "theta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma_sdm",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> theta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> theta_flat__;
        current_statement__ = 3;
        theta_flat__ = context__.vals_r("theta");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(theta, theta_flat__[(pos__ - 1)],
            "assigning variable theta", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(theta);
      local_scalar_t__ sigma_sdm = DUMMY_VAR__;
      current_statement__ = 4;
      sigma_sdm = context__.vals_r("sigma_sdm")[(1 - 1)];
      out__.write_free_lb(0, sigma_sdm);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"rho", "beta", "theta", "sigma_sdm"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"rho_out"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sdm");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "rho_out");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "theta" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sdm");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "rho_out");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sdm\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"theta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sdm\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + K_pred) + K_pred) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((1 + K_pred) + K_pred) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (1);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stan_1_SDM_NASC_namespace::model_stan_1_SDM_NASC;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stan_1_SDM_NASC_namespace::profiles__;
}
#endif
#endif
