// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stan_1_SAR_NASC_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 116> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 55, column 2 to column 30)",
  " (in 'string', line 56, column 2 to column 22)",
  " (in 'string', line 57, column 2 to column 22)",
  " (in 'string', line 58, column 2 to column 23)",
  " (in 'string', line 59, column 2 to column 28)",
  " (in 'string', line 60, column 2 to column 28)",
  " (in 'string', line 61, column 2 to column 26)",
  " (in 'string', line 64, column 2 to column 45)",
  " (in 'string', line 65, column 2 to column 45)",
  " (in 'string', line 89, column 2 to column 21)",
  " (in 'string', line 91, column 2 to column 27)",
  " (in 'string', line 98, column 2 to column 45)",
  " (in 'string', line 99, column 2 to column 45)",
  " (in 'string', line 100, column 2 to column 45)",
  " (in 'string', line 96, column 6 to column 36)",
  " (in 'string', line 94, column 6 to column 46)",
  " (in 'string', line 93, column 4 to line 96, column 36)",
  " (in 'string', line 92, column 22 to line 97, column 3)",
  " (in 'string', line 92, column 2 to line 97, column 3)",
  " (in 'string', line 68, column 2 to column 29)",
  " (in 'string', line 69, column 2 to column 29)",
  " (in 'string', line 70, column 2 to column 29)",
  " (in 'string', line 71, column 2 to column 29)",
  " (in 'string', line 72, column 2 to column 27)",
  " (in 'string', line 73, column 2 to column 27)",
  " (in 'string', line 74, column 2 to column 36)",
  " (in 'string', line 75, column 2 to column 37)",
  " (in 'string', line 76, column 2 to line 78, column 5)",
  " (in 'string', line 79, column 2 to column 27)",
  " (in 'string', line 80, column 9 to column 10)",
  " (in 'string', line 80, column 12 to column 14)",
  " (in 'string', line 80, column 2 to column 34)",
  " (in 'string', line 82, column 4 to column 29)",
  " (in 'string', line 81, column 2 to line 82, column 29)",
  " (in 'string', line 85, column 6 to column 38)",
  " (in 'string', line 84, column 4 to line 85, column 38)",
  " (in 'string', line 83, column 2 to line 85, column 38)",
  " (in 'string', line 86, column 2 to column 62)",
  " (in 'string', line 3, column 2 to column 22)",
  " (in 'string', line 4, column 2 to column 17)",
  " (in 'string', line 5, column 2 to column 18)",
  " (in 'string', line 6, column 8 to column 10)",
  " (in 'string', line 6, column 19 to column 25)",
  " (in 'string', line 6, column 2 to column 30)",
  " (in 'string', line 7, column 8 to column 10)",
  " (in 'string', line 7, column 19 to column 25)",
  " (in 'string', line 7, column 27 to column 28)",
  " (in 'string', line 7, column 2 to column 33)",
  " (in 'string', line 8, column 9 to column 14)",
  " (in 'string', line 8, column 16 to column 18)",
  " (in 'string', line 8, column 2 to column 28)",
  " (in 'string', line 9, column 9 to column 14)",
  " (in 'string', line 9, column 16 to column 21)",
  " (in 'string', line 9, column 2 to column 25)",
  " (in 'string', line 10, column 9 to column 14)",
  " (in 'string', line 10, column 2 to column 28)",
  " (in 'string', line 11, column 9 to column 14)",
  " (in 'string', line 11, column 2 to column 28)",
  " (in 'string', line 14, column 2 to column 16)",
  " (in 'string', line 16, column 2 to column 41)",
  " (in 'string', line 17, column 2 to column 39)",
  " (in 'string', line 18, column 9 to column 10)",
  " (in 'string', line 18, column 12 to column 14)",
  " (in 'string', line 18, column 2 to column 51)",
  " (in 'string', line 19, column 9 to column 10)",
  " (in 'string', line 19, column 12 to column 14)",
  " (in 'string', line 19, column 2 to column 35)",
  " (in 'string', line 20, column 9 to column 15)",
  " (in 'string', line 20, column 2 to column 22)",
  " (in 'string', line 21, column 8 to column 14)",
  " (in 'string', line 21, column 23 to column 24)",
  " (in 'string', line 21, column 26 to column 28)",
  " (in 'string', line 21, column 2 to column 36)",
  " (in 'string', line 22, column 9 to column 15)",
  " (in 'string', line 22, column 2 to column 30)",
  " (in 'string', line 24, column 11 to column 12)",
  " (in 'string', line 24, column 14 to column 16)",
  " (in 'string', line 24, column 4 to column 21)",
  " (in 'string', line 27, column 8 to column 31)",
  " (in 'string', line 26, column 6 to line 27, column 31)",
  " (in 'string', line 28, column 6 to column 26)",
  " (in 'string', line 25, column 20 to line 29, column 5)",
  " (in 'string', line 25, column 4 to line 29, column 5)",
  " (in 'string', line 30, column 4 to column 33)",
  " (in 'string', line 31, column 4 to column 31)",
  " (in 'string', line 32, column 4 to column 16)",
  " (in 'string', line 49, column 6 to column 47)",
  " (in 'string', line 50, column 6 to column 26)",
  " (in 'string', line 48, column 11 to line 51, column 5)",
  " (in 'string', line 34, column 13 to column 14)",
  " (in 'string', line 34, column 16 to column 18)",
  " (in 'string', line 34, column 6 to column 42)",
  " (in 'string', line 35, column 6 to column 26)",
  " (in 'string', line 37, column 8 to column 42)",
  " (in 'string', line 38, column 8 to column 55)",
  " (in 'string', line 36, column 21 to line 39, column 7)",
  " (in 'string', line 36, column 6 to line 39, column 7)",
  " (in 'string', line 40, column 6 to column 22)",
  " (in 'string', line 45, column 8 to column 49)",
  " (in 'string', line 46, column 8 to column 28)",
  " (in 'string', line 44, column 13 to line 47, column 7)",
  " (in 'string', line 42, column 8 to column 33)",
  " (in 'string', line 43, column 8 to column 28)",
  " (in 'string', line 41, column 30 to line 44, column 7)",
  " (in 'string', line 41, column 6 to line 47, column 7)",
  " (in 'string', line 33, column 19 to line 48, column 5)",
  " (in 'string', line 33, column 4 to line 51, column 5)",
  " (in 'string', line 23, column 22 to line 52, column 3)",
  " (in 'string', line 23, column 2 to line 52, column 3)",
  " (in 'string', line 56, column 9 to column 15)",
  " (in 'string', line 57, column 9 to column 10)",
  " (in 'string', line 58, column 9 to column 11)",
  " (in 'string', line 64, column 9 to column 10)",
  " (in 'string', line 65, column 9 to column 11)",
  " (in 'string', line 91, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_stan_1_SAR_NASC final : public model_base_crtp<model_stan_1_SAR_NASC> {
private:
  int K_pred;
  int J;
  int T0;
  std::vector<Eigen::Matrix<double,-1,1>> X1;
  std::vector<Eigen::Matrix<double,-1,-1>> X0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_data__;
  Eigen::Matrix<double,-1,1> lambda_W_re_data__;
  Eigen::Matrix<double,-1,1> lambda_W_im_data__;
  int N;
  double mean_y;
  double sd_y;
  Eigen::Matrix<double,-1,-1> Y_std_data__;
  Eigen::Matrix<double,-1,-1> WY_std_data__;
  Eigen::Matrix<double,-1,1> sd_x_data__;
  std::vector<Eigen::Matrix<double,-1,-1>> X_std;
  Eigen::Matrix<double,-1,1> x_identified_data__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> lambda_W_re{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> lambda_W_im{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> WY_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sd_x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> x_identified{nullptr, 0};
public:
  ~model_stan_1_SAR_NASC() {}
  model_stan_1_SAR_NASC(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stan_1_SAR_NASC_namespace::model_stan_1_SAR_NASC";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 39;
      context__.validate_dims("data initialization", "K_pred", "int",
        std::vector<size_t>{});
      K_pred = std::numeric_limits<int>::min();
      current_statement__ = 39;
      K_pred = context__.vals_i("K_pred")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "K_pred", K_pred, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 40;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 41;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("X1", "T0", T0);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("X1", "K_pred", K_pred);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "X1", "double",
        std::vector<size_t>{static_cast<size_t>(T0),
          static_cast<size_t>(K_pred)});
      X1 = std::vector<Eigen::Matrix<double,-1,1>>(T0,
             Eigen::Matrix<double,-1,1>::Constant(K_pred,
               std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X1_flat__;
        current_statement__ = 44;
        X1_flat__ = context__.vals_r("X1");
        current_statement__ = 44;
        pos__ = 1;
        current_statement__ = 44;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 44;
          for (int sym2__ = 1; sym2__ <= T0; ++sym2__) {
            current_statement__ = 44;
            stan::model::assign(X1, X1_flat__[(pos__ - 1)],
              "assigning variable X1", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 44;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("X0", "T0", T0);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("X0", "K_pred", K_pred);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("X0", "J", J);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "X0", "double",
        std::vector<size_t>{static_cast<size_t>(T0),
          static_cast<size_t>(K_pred), static_cast<size_t>(J)});
      X0 = std::vector<Eigen::Matrix<double,-1,-1>>(T0,
             Eigen::Matrix<double,-1,-1>::Constant(K_pred, J,
               std::numeric_limits<double>::quiet_NaN()));
      {
        std::vector<local_scalar_t__> X0_flat__;
        current_statement__ = 48;
        X0_flat__ = context__.vals_r("X0");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 48;
          for (int sym2__ = 1; sym2__ <= K_pred; ++sym2__) {
            current_statement__ = 48;
            for (int sym3__ = 1; sym3__ <= T0; ++sym3__) {
              current_statement__ = 48;
              stan::model::assign(X0, X0_flat__[(pos__ - 1)],
                "assigning variable X0", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 48;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 49;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 50;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 51;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 51;
        pos__ = 1;
        current_statement__ = 51;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 51;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 51;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 51;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 52;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 53;
      stan::math::validate_non_negative_index("W", "J + 1", (J + 1));
      current_statement__ = 54;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>((J + 1))});
      W_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), (J + 1),
                   std::numeric_limits<double>::quiet_NaN());
      new (&W) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_data__.data(), (J +
        1), (J + 1));
      {
        std::vector<local_scalar_t__> W_flat__;
        current_statement__ = 54;
        W_flat__ = context__.vals_r("W");
        current_statement__ = 54;
        pos__ = 1;
        current_statement__ = 54;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 54;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 54;
            stan::model::assign(W, W_flat__[(pos__ - 1)],
              "assigning variable W", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 54;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("lambda_W_re", "J + 1", (J + 1));
      current_statement__ = 56;
      context__.validate_dims("data initialization", "lambda_W_re", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1))});
      lambda_W_re_data__ = Eigen::Matrix<double,-1,1>::Constant((J + 1),
                             std::numeric_limits<double>::quiet_NaN());
      new (&lambda_W_re)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(lambda_W_re_data__.data(), (J
        + 1));
      {
        std::vector<local_scalar_t__> lambda_W_re_flat__;
        current_statement__ = 56;
        lambda_W_re_flat__ = context__.vals_r("lambda_W_re");
        current_statement__ = 56;
        pos__ = 1;
        current_statement__ = 56;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 56;
          stan::model::assign(lambda_W_re, lambda_W_re_flat__[(pos__ - 1)],
            "assigning variable lambda_W_re", stan::model::index_uni(sym1__));
          current_statement__ = 56;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      stan::math::validate_non_negative_index("lambda_W_im", "J + 1", (J + 1));
      current_statement__ = 58;
      context__.validate_dims("data initialization", "lambda_W_im", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1))});
      lambda_W_im_data__ = Eigen::Matrix<double,-1,1>::Constant((J + 1),
                             std::numeric_limits<double>::quiet_NaN());
      new (&lambda_W_im)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(lambda_W_im_data__.data(), (J
        + 1));
      {
        std::vector<local_scalar_t__> lambda_W_im_flat__;
        current_statement__ = 58;
        lambda_W_im_flat__ = context__.vals_r("lambda_W_im");
        current_statement__ = 58;
        pos__ = 1;
        current_statement__ = 58;
        for (int sym1__ = 1; sym1__ <= (J + 1); ++sym1__) {
          current_statement__ = 58;
          stan::model::assign(lambda_W_im, lambda_W_im_flat__[(pos__ - 1)],
            "assigning variable lambda_W_im", stan::model::index_uni(sym1__));
          current_statement__ = 58;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 59;
      N = std::numeric_limits<int>::min();
      current_statement__ = 59;
      N = (J + 1);
      current_statement__ = 60;
      mean_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 60;
      mean_y = stan::math::mean(stan::math::to_vector(Y_panel));
      current_statement__ = 61;
      sd_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 61;
      sd_y = stan::math::sd(stan::math::to_vector(Y_panel));
      current_statement__ = 62;
      stan::math::validate_non_negative_index("Y_std", "N", N);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("Y_std", "T0", T0);
      current_statement__ = 64;
      Y_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                       std::numeric_limits<double>::quiet_NaN());
      new (&Y_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_std_data__.data(), N, T0);
      current_statement__ = 64;
      stan::model::assign(Y_std,
        stan::math::divide(stan::math::subtract(Y_panel, mean_y), sd_y),
        "assigning variable Y_std");
      current_statement__ = 65;
      stan::math::validate_non_negative_index("WY_std", "N", N);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("WY_std", "T0", T0);
      current_statement__ = 67;
      WY_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                        std::numeric_limits<double>::quiet_NaN());
      new (&WY_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(WY_std_data__.data(), N, T0);
      current_statement__ = 67;
      stan::model::assign(WY_std, stan::math::multiply(W, Y_std),
        "assigning variable WY_std");
      current_statement__ = 68;
      stan::math::validate_non_negative_index("sd_x", "K_pred", K_pred);
      current_statement__ = 69;
      sd_x_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                      std::numeric_limits<double>::quiet_NaN());
      new (&sd_x) Eigen::Map<Eigen::Matrix<double,-1,1>>(sd_x_data__.data(),
        K_pred);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("X_std", "K_pred", K_pred);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("X_std", "N", N);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("X_std", "T0", T0);
      current_statement__ = 73;
      X_std = std::vector<Eigen::Matrix<double,-1,-1>>(K_pred,
                Eigen::Matrix<double,-1,-1>::Constant(N, T0,
                  std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 74;
      stan::math::validate_non_negative_index("x_identified", "K_pred",
        K_pred);
      current_statement__ = 75;
      x_identified_data__ = Eigen::Matrix<double,-1,1>::Constant(K_pred,
                              std::numeric_limits<double>::quiet_NaN());
      new (&x_identified)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(x_identified_data__.data(),
        K_pred);
      current_statement__ = 109;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 76;
        stan::math::validate_non_negative_index("Xk", "N", N);
        current_statement__ = 77;
        stan::math::validate_non_negative_index("Xk", "T0", T0);
        Eigen::Matrix<double,-1,-1> Xk =
          Eigen::Matrix<double,-1,-1>::Constant(N, T0,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 83;
        for (int t = 1; t <= T0; ++t) {
          current_statement__ = 80;
          for (int j = 1; j <= J; ++j) {
            current_statement__ = 79;
            stan::model::assign(Xk,
              stan::model::rvalue(X0, "X0", stan::model::index_uni(t),
                stan::model::index_uni(k), stan::model::index_uni(j)),
              "assigning variable Xk", stan::model::index_uni(j),
              stan::model::index_uni(t));
          }
          current_statement__ = 81;
          stan::model::assign(Xk,
            stan::model::rvalue(X1, "X1", stan::model::index_uni(t),
              stan::model::index_uni(k)), "assigning variable Xk",
            stan::model::index_uni(N), stan::model::index_uni(t));
        }
        double m = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 84;
        m = stan::math::mean(stan::math::to_vector(Xk));
        double s = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 85;
        s = stan::math::sd(stan::math::to_vector(Xk));
        current_statement__ = 86;
        stan::model::assign(sd_x, s, "assigning variable sd_x",
          stan::model::index_uni(k));
        current_statement__ = 107;
        if (stan::math::logical_gt(s, 1e-12)) {
          current_statement__ = 90;
          stan::math::validate_non_negative_index("Xk_std", "N", N);
          current_statement__ = 91;
          stan::math::validate_non_negative_index("Xk_std", "T0", T0);
          Eigen::Matrix<double,-1,-1> Xk_std =
            Eigen::Matrix<double,-1,-1>::Constant(N, T0,
              std::numeric_limits<double>::quiet_NaN());
          current_statement__ = 92;
          stan::model::assign(Xk_std,
            stan::math::divide(stan::math::subtract(Xk, m), s),
            "assigning variable Xk_std");
          double within_var = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 93;
          within_var = 0;
          current_statement__ = 97;
          for (int i = 1; i <= N; ++i) {
            double row_mean = std::numeric_limits<double>::quiet_NaN();
            current_statement__ = 94;
            row_mean = stan::math::mean(
                         stan::model::rvalue(Xk_std, "Xk_std",
                           stan::model::index_uni(i),
                           stan::model::index_omni()));
            current_statement__ = 95;
            within_var = (within_var +
              stan::math::variance(
                stan::math::subtract(
                  stan::model::rvalue(Xk_std, "Xk_std",
                    stan::model::index_uni(i), stan::model::index_omni()),
                  row_mean)));
          }
          current_statement__ = 98;
          within_var = (within_var / N);
          current_statement__ = 105;
          if (stan::math::logical_gt(within_var, 1e-10)) {
            current_statement__ = 102;
            stan::model::assign(X_std, Xk_std, "assigning variable X_std",
              stan::model::index_uni(k));
            current_statement__ = 103;
            stan::model::assign(x_identified, 1,
              "assigning variable x_identified", stan::model::index_uni(k));
          } else {
            current_statement__ = 99;
            stan::model::assign(X_std, stan::math::rep_matrix(0.0, N, T0),
              "assigning variable X_std", stan::model::index_uni(k));
            current_statement__ = 100;
            stan::model::assign(x_identified, 0,
              "assigning variable x_identified", stan::model::index_uni(k));
          }
        } else {
          current_statement__ = 87;
          stan::model::assign(X_std, stan::math::rep_matrix(0.0, N, T0),
            "assigning variable X_std", stan::model::index_uni(k));
          current_statement__ = 88;
          stan::model::assign(x_identified, 0,
            "assigning variable x_identified", stan::model::index_uni(k));
        }
      }
      current_statement__ = 110;
      stan::math::validate_non_negative_index("beta", "K_pred", K_pred);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("alpha_raw", "N", N);
      current_statement__ = 112;
      stan::math::validate_non_negative_index("gamma_raw", "T0", T0);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("alpha", "N", N);
      current_statement__ = 114;
      stan::math::validate_non_negative_index("gamma", "T0", T0);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("beta_orig", "K_pred", K_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + K_pred + N + T0 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_stan_1_SAR_NASC";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stan_1_SAR_NASC_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      alpha_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T0, DUMMY_VAR__);
      current_statement__ = 4;
      gamma_raw = in__.template read<
                    Eigen::Matrix<local_scalar_t__,-1,1>>(T0);
      local_scalar_t__ sigma_alpha = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_alpha = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      local_scalar_t__ sigma_gamma = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_gamma = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sar = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(alpha,
        stan::math::multiply(sigma_alpha, alpha_raw),
        "assigning variable alpha");
      Eigen::Matrix<local_scalar_t__,-1,1> gamma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T0, DUMMY_VAR__);
      current_statement__ = 9;
      stan::model::assign(gamma,
        stan::math::multiply(sigma_gamma, gamma_raw),
        "assigning variable gamma");
      {
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_sar, 0, 1));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_alpha, 0, 2));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_gamma, 0, 2));
        current_statement__ = 24;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(alpha_raw));
        current_statement__ = 25;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(gamma_raw));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::sum(alpha), 0, (0.001 * N)));
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::sum(gamma), 0, (0.001 * T0)));
        local_scalar_t__ log_det_A = DUMMY_VAR__;
        current_statement__ = 28;
        log_det_A = (0.5 *
          stan::math::sum(
            stan::math::log(
              stan::math::add(
                stan::math::square(
                  stan::math::subtract(1,
                    stan::math::multiply(rho, lambda_W_re))),
                stan::math::square(stan::math::multiply(rho, lambda_W_im))))));
        current_statement__ = 29;
        lp_accum__.add((T0 * log_det_A));
        current_statement__ = 30;
        stan::math::validate_non_negative_index("mu", "N", N);
        current_statement__ = 31;
        stan::math::validate_non_negative_index("mu", "T0", T0);
        Eigen::Matrix<local_scalar_t__,-1,-1> mu =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(N, T0, DUMMY_VAR__);
        current_statement__ = 32;
        stan::model::assign(mu, stan::math::multiply(rho, WY_std),
          "assigning variable mu");
        current_statement__ = 34;
        for (int k = 1; k <= K_pred; ++k) {
          current_statement__ = 33;
          stan::model::assign(mu,
            stan::math::add(stan::model::deep_copy(mu),
              stan::math::multiply(
                stan::model::rvalue(beta, "beta", stan::model::index_uni(k)),
                stan::model::rvalue(X_std, "X_std", stan::model::index_uni(k)))),
            "assigning variable mu");
        }
        current_statement__ = 37;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 36;
          for (int t = 1; t <= T0; ++t) {
            current_statement__ = 35;
            stan::model::assign(mu,
              (stan::model::rvalue(mu, "mu", stan::model::index_uni(i),
                 stan::model::index_uni(t)) +
              (stan::model::rvalue(alpha, "alpha", stan::model::index_uni(i))
              +
              stan::model::rvalue(gamma, "gamma", stan::model::index_uni(t)))),
              "assigning variable mu", stan::model::index_uni(i),
              stan::model::index_uni(t));
          }
        }
        current_statement__ = 38;
        lp_accum__.add(stan::math::normal_lpdf<false>(
                         stan::math::to_vector(
                           stan::math::subtract(Y_std, mu)), 0, sigma_sar));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stan_1_SAR_NASC_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      rho = in__.template read_constrain_lub<local_scalar_t__,
              jacobian__>(-1, 1, lp__);
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred);
      Eigen::Matrix<double,-1,1> alpha_raw =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      alpha_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      Eigen::Matrix<double,-1,1> gamma_raw =
        Eigen::Matrix<double,-1,1>::Constant(T0,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      gamma_raw = in__.template read<
                    Eigen::Matrix<local_scalar_t__,-1,1>>(T0);
      double sigma_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma_alpha = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      double sigma_gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      sigma_gamma = in__.template read_constrain_lb<local_scalar_t__,
                      jacobian__>(0, lp__);
      double sigma_sar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      sigma_sar = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> alpha =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> gamma =
        Eigen::Matrix<double,-1,1>::Constant(T0,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(rho);
      out__.write(beta);
      out__.write(alpha_raw);
      out__.write(gamma_raw);
      out__.write(sigma_alpha);
      out__.write(sigma_gamma);
      out__.write(sigma_sar);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 8;
      stan::model::assign(alpha,
        stan::math::multiply(sigma_alpha, alpha_raw),
        "assigning variable alpha");
      current_statement__ = 9;
      stan::model::assign(gamma,
        stan::math::multiply(sigma_gamma, gamma_raw),
        "assigning variable gamma");
      if (emit_transformed_parameters__) {
        out__.write(alpha);
        out__.write(gamma);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      double rho_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      rho_out = rho;
      Eigen::Matrix<double,-1,1> beta_orig =
        Eigen::Matrix<double,-1,1>::Constant(K_pred,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 19;
      for (int k = 1; k <= K_pred; ++k) {
        current_statement__ = 17;
        if (stan::math::logical_gt(
              stan::model::rvalue(x_identified, "x_identified",
                stan::model::index_uni(k)), 0.5)) {
          current_statement__ = 16;
          stan::model::assign(beta_orig,
            ((stan::model::rvalue(beta, "beta", stan::model::index_uni(k)) *
            sd_y) /
            stan::model::rvalue(sd_x, "sd_x", stan::model::index_uni(k))),
            "assigning variable beta_orig", stan::model::index_uni(k));
        } else {
          current_statement__ = 15;
          stan::model::assign(beta_orig, stan::math::not_a_number(),
            "assigning variable beta_orig", stan::model::index_uni(k));
        }
      }
      double sigma_alpha_orig = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      sigma_alpha_orig = (sigma_alpha * sd_y);
      double sigma_gamma_orig = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      sigma_gamma_orig = (sigma_gamma * sd_y);
      double sigma_sar_orig = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      sigma_sar_orig = (sigma_sar * sd_y);
      out__.write(rho_out);
      out__.write(beta_orig);
      out__.write(sigma_alpha_orig);
      out__.write(sigma_gamma_orig);
      out__.write(sigma_sar_orig);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K_pred),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(alpha_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable alpha_raw");
      out__.write(alpha_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T0, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(gamma_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(T0),
        "assigning variable gamma_raw");
      out__.write(gamma_raw);
      local_scalar_t__ sigma_alpha = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_alpha);
      local_scalar_t__ sigma_gamma = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_gamma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_gamma);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sar = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sar);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(K_pred)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "alpha_raw",
        "double", std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "gamma_raw",
        "double", std::vector<size_t>{static_cast<size_t>(T0)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "sigma_alpha",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "sigma_gamma",
        "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "sigma_sar",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 1;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(-1, 1, rho);
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K_pred, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 2;
        beta_flat__ = context__.vals_r("beta");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> alpha_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> alpha_raw_flat__;
        current_statement__ = 3;
        alpha_raw_flat__ = context__.vals_r("alpha_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(alpha_raw, alpha_raw_flat__[(pos__ - 1)],
            "assigning variable alpha_raw", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(alpha_raw);
      Eigen::Matrix<local_scalar_t__,-1,1> gamma_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(T0, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> gamma_raw_flat__;
        current_statement__ = 4;
        gamma_raw_flat__ = context__.vals_r("gamma_raw");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(gamma_raw, gamma_raw_flat__[(pos__ - 1)],
            "assigning variable gamma_raw", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(gamma_raw);
      local_scalar_t__ sigma_alpha = DUMMY_VAR__;
      current_statement__ = 5;
      sigma_alpha = context__.vals_r("sigma_alpha")[(1 - 1)];
      out__.write_free_lb(0, sigma_alpha);
      local_scalar_t__ sigma_gamma = DUMMY_VAR__;
      current_statement__ = 6;
      sigma_gamma = context__.vals_r("sigma_gamma")[(1 - 1)];
      out__.write_free_lb(0, sigma_gamma);
      local_scalar_t__ sigma_sar = DUMMY_VAR__;
      current_statement__ = 7;
      sigma_sar = context__.vals_r("sigma_sar")[(1 - 1)];
      out__.write_free_lb(0, sigma_sar);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"rho", "beta", "alpha_raw",
                "gamma_raw", "sigma_alpha", "sigma_gamma", "sigma_sar"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"alpha", "gamma"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"rho_out", "beta_orig", "sigma_alpha_orig", "sigma_gamma_orig",
             "sigma_sar_orig"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(K_pred)},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{static_cast<size_t>(T0)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(T0)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(K_pred)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_alpha");
    param_names__.emplace_back(std::string() + "sigma_gamma");
    param_names__.emplace_back(std::string() + "sigma_sar");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "gamma" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "rho_out");
      for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_orig" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma_alpha_orig");
      param_names__.emplace_back(std::string() + "sigma_gamma_orig");
      param_names__.emplace_back(std::string() + "sigma_sar_orig");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "alpha_raw" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
      param_names__.emplace_back(std::string() + "gamma_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_alpha");
    param_names__.emplace_back(std::string() + "sigma_gamma");
    param_names__.emplace_back(std::string() + "sigma_sar");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "alpha" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "gamma" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "rho_out");
      for (int sym1__ = 1; sym1__ <= K_pred; ++sym1__) {
        param_names__.emplace_back(std::string() + "beta_orig" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "sigma_alpha_orig");
      param_names__.emplace_back(std::string() + "sigma_gamma_orig");
      param_names__.emplace_back(std::string() + "sigma_sar_orig");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"alpha_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"gamma_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_sar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_orig\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma_alpha_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_gamma_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_sar_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"parameters\"},{\"name\":\"alpha_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"gamma_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"parameters\"},{\"name\":\"sigma_alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_sar\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"transformed_parameters\"},{\"name\":\"rho_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_orig\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K_pred) + "},\"block\":\"generated_quantities\"},{\"name\":\"sigma_alpha_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_gamma_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_sar_orig\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + K_pred) + N) + T0) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N + T0));
    const size_t num_gen_quantities = emit_generated_quantities * (((((1 +
      K_pred) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((1 + K_pred) + N) + T0) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * ((N + T0));
    const size_t num_gen_quantities = emit_generated_quantities * (((((1 +
      K_pred) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stan_1_SAR_NASC_namespace::model_stan_1_SAR_NASC;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stan_1_SAR_NASC_namespace::profiles__;
}
#endif
#endif
