// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stan_2_NASC_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 102> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 73, column 2 to column 18)",
  " (in 'string', line 74, column 2 to column 26)",
  " (in 'string', line 78, column 2 to column 73)",
  " (in 'string', line 93, column 2 to column 27)",
  " (in 'string', line 94, column 2 to column 34)",
  " (in 'string', line 95, column 2 to column 43)",
  " (in 'string', line 96, column 2 to line 98, column 31)",
  " (in 'string', line 105, column 2 to column 45)",
  " (in 'string', line 106, column 2 to column 27)",
  " (in 'string', line 107, column 2 to column 32)",
  " (in 'string', line 108, column 2 to column 35)",
  " (in 'string', line 109, column 2 to column 36)",
  " (in 'string', line 100, column 4 to line 101, column 35)",
  " (in 'string', line 99, column 2 to line 101, column 35)",
  " (in 'string', line 103, column 4 to line 104, column 42)",
  " (in 'string', line 102, column 2 to line 104, column 42)",
  " (in 'string', line 81, column 2 to column 30)",
  " (in 'string', line 83, column 4 to column 52)",
  " (in 'string', line 82, column 2 to line 83, column 52)",
  " (in 'string', line 84, column 2 to column 61)",
  " (in 'string', line 87, column 6 to line 89, column 55)",
  " (in 'string', line 86, column 4 to line 89, column 55)",
  " (in 'string', line 85, column 21 to line 90, column 3)",
  " (in 'string', line 85, column 2 to line 90, column 3)",
  " (in 'string', line 3, column 2 to column 17)",
  " (in 'string', line 4, column 2 to column 18)",
  " (in 'string', line 5, column 9 to column 14)",
  " (in 'string', line 5, column 16 to column 18)",
  " (in 'string', line 5, column 2 to column 28)",
  " (in 'string', line 6, column 9 to column 10)",
  " (in 'string', line 6, column 12 to column 13)",
  " (in 'string', line 6, column 2 to column 19)",
  " (in 'string', line 7, column 9 to column 10)",
  " (in 'string', line 7, column 2 to column 17)",
  " (in 'string', line 8, column 2 to column 22)",
  " (in 'string', line 9, column 9 to column 15)",
  " (in 'string', line 9, column 17 to column 18)",
  " (in 'string', line 9, column 2 to column 28)",
  " (in 'string', line 10, column 9 to column 15)",
  " (in 'string', line 10, column 2 to column 25)",
  " (in 'string', line 11, column 2 to column 21)",
  " (in 'string', line 12, column 9 to column 14)",
  " (in 'string', line 12, column 16 to column 17)",
  " (in 'string', line 12, column 2 to column 26)",
  " (in 'string', line 13, column 9 to column 14)",
  " (in 'string', line 13, column 2 to column 23)",
  " (in 'string', line 14, column 18 to column 23)",
  " (in 'string', line 14, column 2 to column 31)",
  " (in 'string', line 15, column 2 to column 30)",
  " (in 'string', line 16, column 2 to column 44)",
  " (in 'string', line 17, column 2 to column 36)",
  " (in 'string', line 18, column 2 to column 23)",
  " (in 'string', line 19, column 2 to column 26)",
  " (in 'string', line 22, column 9 to column 10)",
  " (in 'string', line 22, column 12 to column 13)",
  " (in 'string', line 22, column 2 to column 53)",
  " (in 'string', line 23, column 9 to column 11)",
  " (in 'string', line 23, column 2 to column 53)",
  " (in 'string', line 24, column 2 to column 37)",
  " (in 'string', line 25, column 2 to column 35)",
  " (in 'string', line 26, column 9 to column 11)",
  " (in 'string', line 26, column 2 to column 49)",
  " (in 'string', line 27, column 9 to column 11)",
  " (in 'string', line 27, column 13 to column 14)",
  " (in 'string', line 27, column 2 to column 44)",
  " (in 'string', line 28, column 9 to column 11)",
  " (in 'string', line 28, column 13 to column 14)",
  " (in 'string', line 28, column 2 to column 30)",
  " (in 'string', line 29, column 9 to column 15)",
  " (in 'string', line 29, column 17 to column 18)",
  " (in 'string', line 29, column 2 to column 32)",
  " (in 'string', line 31, column 4 to column 54)",
  " (in 'string', line 32, column 4 to column 54)",
  " (in 'string', line 30, column 17 to line 33, column 3)",
  " (in 'string', line 30, column 2 to line 33, column 3)",
  " (in 'string', line 34, column 9 to column 14)",
  " (in 'string', line 34, column 16 to column 17)",
  " (in 'string', line 34, column 2 to column 30)",
  " (in 'string', line 35, column 9 to column 14)",
  " (in 'string', line 35, column 2 to column 30)",
  " (in 'string', line 37, column 4 to column 33)",
  " (in 'string', line 38, column 4 to column 31)",
  " (in 'string', line 43, column 6 to column 47)",
  " (in 'string', line 44, column 6 to column 28)",
  " (in 'string', line 42, column 11 to line 45, column 5)",
  " (in 'string', line 40, column 6 to column 50)",
  " (in 'string', line 41, column 6 to column 50)",
  " (in 'string', line 39, column 21 to line 42, column 5)",
  " (in 'string', line 39, column 4 to line 45, column 5)",
  " (in 'string', line 36, column 21 to line 46, column 3)",
  " (in 'string', line 36, column 2 to line 46, column 3)",
  " (in 'string', line 48, column 9 to column 10)",
  " (in 'string', line 48, column 2 to column 62)",
  " (in 'string', line 49, column 9 to column 10)",
  " (in 'string', line 49, column 2 to column 28)",
  " (in 'string', line 50, column 2 to column 31)",
  " (in 'string', line 51, column 2 to column 26)",
  " (in 'string', line 70, column 2 to column 59)",
  " (in 'string', line 73, column 10 to column 11)",
  " (in 'string', line 93, column 9 to column 11)",
  " (in 'string', line 94, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_stan_2_NASC final : public model_base_crtp<model_stan_2_NASC> {
private:
  int J;
  int T0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_J_data__;
  Eigen::Matrix<double,-1,1> w_J1_data__;
  int T_post;
  Eigen::Matrix<double,-1,-1> Y0_post_data__;
  Eigen::Matrix<double,-1,1> Y1_post_data__;
  int K_cov;
  Eigen::Matrix<double,-1,-1> X_cov0_data__;
  Eigen::Matrix<double,-1,1> X_cov1_data__;
  Eigen::Matrix<double,-1,1> v_cov_data__;
  double rho;
  int use_bias_correction;
  int use_penalty;
  double lambda;
  double sigma_ref;
  Eigen::Matrix<double,-1,-1> I_J_data__;
  Eigen::Matrix<double,-1,1> y_pre_data__;
  double mean_y;
  double sd_y;
  Eigen::Matrix<double,-1,1> y_pre_std_data__;
  Eigen::Matrix<double,-1,-1> X_pre_data__;
  Eigen::Matrix<double,-1,-1> X_pre_std_data__;
  Eigen::Matrix<double,-1,-1> Y0_post_std_data__;
  Eigen::Matrix<double,-1,-1> X_cov0_std_data__;
  Eigen::Matrix<double,-1,1> X_cov1_std_data__;
  Eigen::Matrix<double,-1,1> s_data__;
  Eigen::Matrix<double,-1,1> s_abs_data__;
  double n_eff;
  double sigma_floor;
  double lambda_tilde;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> w_J1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y0_post{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y1_post{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_cov0{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> X_cov1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> v_cov{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> I_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y_pre{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y_pre_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_pre{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_pre_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y0_post_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_cov0_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> X_cov1_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> s{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> s_abs{nullptr, 0};
public:
  ~model_stan_2_NASC() {}
  model_stan_2_NASC(stan::io::var_context& context__, unsigned int
                    random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::model_stan_2_NASC";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 25;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 25;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 26;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 28;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 29;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 29;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 29;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "W_J", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(J)});
      W_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&W_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_J_data__.data(),
        J, J);
      {
        std::vector<local_scalar_t__> W_J_flat__;
        current_statement__ = 32;
        W_J_flat__ = context__.vals_r("W_J");
        current_statement__ = 32;
        pos__ = 1;
        current_statement__ = 32;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 32;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 32;
            stan::model::assign(W_J, W_J_flat__[(pos__ - 1)],
              "assigning variable W_J", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 32;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 33;
      stan::math::validate_non_negative_index("w_J1", "J", J);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "w_J1", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      w_J1_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                      std::numeric_limits<double>::quiet_NaN());
      new (&w_J1) Eigen::Map<Eigen::Matrix<double,-1,1>>(w_J1_data__.data(),
        J);
      {
        std::vector<local_scalar_t__> w_J1_flat__;
        current_statement__ = 34;
        w_J1_flat__ = context__.vals_r("w_J1");
        current_statement__ = 34;
        pos__ = 1;
        current_statement__ = 34;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 34;
          stan::model::assign(w_J1, w_J1_flat__[(pos__ - 1)],
            "assigning variable w_J1", stan::model::index_uni(sym1__));
          current_statement__ = 34;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 35;
      context__.validate_dims("data initialization", "T_post", "int",
        std::vector<size_t>{});
      T_post = std::numeric_limits<int>::min();
      current_statement__ = 35;
      T_post = context__.vals_i("T_post")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "T_post", T_post, 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("Y0_post", "T_post", T_post);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("Y0_post", "J", J);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "Y0_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post),
          static_cast<size_t>(J)});
      Y0_post_data__ = Eigen::Matrix<double,-1,-1>::Constant(T_post, J,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y0_post)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y0_post_data__.data(),
        T_post, J);
      {
        std::vector<local_scalar_t__> Y0_post_flat__;
        current_statement__ = 38;
        Y0_post_flat__ = context__.vals_r("Y0_post");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= T_post; ++sym2__) {
            current_statement__ = 38;
            stan::model::assign(Y0_post, Y0_post_flat__[(pos__ - 1)],
              "assigning variable Y0_post", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 39;
      stan::math::validate_non_negative_index("Y1_post", "T_post", T_post);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "Y1_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post)});
      Y1_post_data__ = Eigen::Matrix<double,-1,1>::Constant(T_post,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y1_post)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y1_post_data__.data(), T_post);
      {
        std::vector<local_scalar_t__> Y1_post_flat__;
        current_statement__ = 40;
        Y1_post_flat__ = context__.vals_r("Y1_post");
        current_statement__ = 40;
        pos__ = 1;
        current_statement__ = 40;
        for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
          current_statement__ = 40;
          stan::model::assign(Y1_post, Y1_post_flat__[(pos__ - 1)],
            "assigning variable Y1_post", stan::model::index_uni(sym1__));
          current_statement__ = 40;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 41;
      context__.validate_dims("data initialization", "K_cov", "int",
        std::vector<size_t>{});
      K_cov = std::numeric_limits<int>::min();
      current_statement__ = 41;
      K_cov = context__.vals_i("K_cov")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "K_cov", K_cov, 0);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("X_cov0", "K_cov", K_cov);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("X_cov0", "J", J);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "X_cov0", "double",
        std::vector<size_t>{static_cast<size_t>(K_cov),
          static_cast<size_t>(J)});
      X_cov0_data__ = Eigen::Matrix<double,-1,-1>::Constant(K_cov, J,
                        std::numeric_limits<double>::quiet_NaN());
      new (&X_cov0)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_cov0_data__.data(), K_cov,
        J);
      {
        std::vector<local_scalar_t__> X_cov0_flat__;
        current_statement__ = 44;
        X_cov0_flat__ = context__.vals_r("X_cov0");
        current_statement__ = 44;
        pos__ = 1;
        current_statement__ = 44;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 44;
          for (int sym2__ = 1; sym2__ <= K_cov; ++sym2__) {
            current_statement__ = 44;
            stan::model::assign(X_cov0, X_cov0_flat__[(pos__ - 1)],
              "assigning variable X_cov0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 44;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("X_cov1", "K_cov", K_cov);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "X_cov1", "double",
        std::vector<size_t>{static_cast<size_t>(K_cov)});
      X_cov1_data__ = Eigen::Matrix<double,-1,1>::Constant(K_cov,
                        std::numeric_limits<double>::quiet_NaN());
      new (&X_cov1)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(X_cov1_data__.data(), K_cov);
      {
        std::vector<local_scalar_t__> X_cov1_flat__;
        current_statement__ = 46;
        X_cov1_flat__ = context__.vals_r("X_cov1");
        current_statement__ = 46;
        pos__ = 1;
        current_statement__ = 46;
        for (int sym1__ = 1; sym1__ <= K_cov; ++sym1__) {
          current_statement__ = 46;
          stan::model::assign(X_cov1, X_cov1_flat__[(pos__ - 1)],
            "assigning variable X_cov1", stan::model::index_uni(sym1__));
          current_statement__ = 46;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 47;
      stan::math::validate_non_negative_index("v_cov", "K_cov", K_cov);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "v_cov", "double",
        std::vector<size_t>{static_cast<size_t>(K_cov)});
      v_cov_data__ = Eigen::Matrix<double,-1,1>::Constant(K_cov,
                       std::numeric_limits<double>::quiet_NaN());
      new (&v_cov)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(v_cov_data__.data(), K_cov);
      {
        std::vector<local_scalar_t__> v_cov_flat__;
        current_statement__ = 48;
        v_cov_flat__ = context__.vals_r("v_cov");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= K_cov; ++sym1__) {
          current_statement__ = 48;
          stan::model::assign(v_cov, v_cov_flat__[(pos__ - 1)],
            "assigning variable v_cov", stan::model::index_uni(sym1__));
          current_statement__ = 48;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 48;
      stan::math::check_greater_or_equal(function__, "v_cov", v_cov, 0);
      current_statement__ = 49;
      context__.validate_dims("data initialization", "rho", "double",
        std::vector<size_t>{});
      rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      rho = context__.vals_r("rho")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "rho", rho, -1);
      current_statement__ = 49;
      stan::math::check_less_or_equal(function__, "rho", rho, 1);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "use_bias_correction",
        "int", std::vector<size_t>{});
      use_bias_correction = std::numeric_limits<int>::min();
      current_statement__ = 50;
      use_bias_correction = context__.vals_i("use_bias_correction")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "use_bias_correction",
        use_bias_correction, 0);
      current_statement__ = 50;
      stan::math::check_less_or_equal(function__, "use_bias_correction",
        use_bias_correction, 1);
      current_statement__ = 51;
      context__.validate_dims("data initialization", "use_penalty", "int",
        std::vector<size_t>{});
      use_penalty = std::numeric_limits<int>::min();
      current_statement__ = 51;
      use_penalty = context__.vals_i("use_penalty")[(1 - 1)];
      current_statement__ = 51;
      stan::math::check_greater_or_equal(function__, "use_penalty",
        use_penalty, 0);
      current_statement__ = 51;
      stan::math::check_less_or_equal(function__, "use_penalty", use_penalty,
        1);
      current_statement__ = 52;
      context__.validate_dims("data initialization", "lambda", "double",
        std::vector<size_t>{});
      lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 52;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      current_statement__ = 52;
      stan::math::check_greater_or_equal(function__, "lambda", lambda, 0);
      current_statement__ = 53;
      context__.validate_dims("data initialization", "sigma_ref", "double",
        std::vector<size_t>{});
      sigma_ref = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 53;
      sigma_ref = context__.vals_r("sigma_ref")[(1 - 1)];
      current_statement__ = 53;
      stan::math::check_greater_or_equal(function__, "sigma_ref", sigma_ref,
        0);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 56;
      I_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&I_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(I_J_data__.data(),
        J, J);
      current_statement__ = 56;
      stan::model::assign(I_J,
        stan::math::diag_matrix(stan::math::rep_vector(1.0, J)),
        "assigning variable I_J");
      current_statement__ = 57;
      stan::math::validate_non_negative_index("y_pre", "T0", T0);
      current_statement__ = 58;
      y_pre_data__ = Eigen::Matrix<double,-1,1>::Constant(T0,
                       std::numeric_limits<double>::quiet_NaN());
      new (&y_pre)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(y_pre_data__.data(), T0);
      current_statement__ = 58;
      stan::model::assign(y_pre,
        stan::math::to_vector(
          stan::model::rvalue(Y_panel, "Y_panel",
            stan::model::index_uni((J + 1)), stan::model::index_omni())),
        "assigning variable y_pre");
      current_statement__ = 59;
      mean_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 59;
      mean_y = stan::math::mean(y_pre);
      current_statement__ = 60;
      sd_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 60;
      sd_y = stan::math::sd(y_pre);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("y_pre_std", "T0", T0);
      current_statement__ = 62;
      y_pre_std_data__ = Eigen::Matrix<double,-1,1>::Constant(T0,
                           std::numeric_limits<double>::quiet_NaN());
      new (&y_pre_std)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(y_pre_std_data__.data(), T0);
      current_statement__ = 62;
      stan::model::assign(y_pre_std,
        stan::math::divide(stan::math::subtract(y_pre, mean_y), sd_y),
        "assigning variable y_pre_std");
      current_statement__ = 63;
      stan::math::validate_non_negative_index("X_pre", "T0", T0);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("X_pre", "J", J);
      current_statement__ = 65;
      X_pre_data__ = Eigen::Matrix<double,-1,-1>::Constant(T0, J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_pre)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_pre_data__.data(), T0, J);
      current_statement__ = 65;
      stan::model::assign(X_pre,
        stan::math::transpose(
          stan::model::rvalue(Y_panel, "Y_panel",
            stan::model::index_min_max(1, J), stan::model::index_omni())),
        "assigning variable X_pre");
      current_statement__ = 66;
      stan::math::validate_non_negative_index("X_pre_std", "T0", T0);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("X_pre_std", "J", J);
      current_statement__ = 68;
      X_pre_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(T0, J,
                           std::numeric_limits<double>::quiet_NaN());
      new (&X_pre_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_pre_std_data__.data(), T0,
        J);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("Y0_post_std", "T_post", T_post);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("Y0_post_std", "J", J);
      current_statement__ = 71;
      Y0_post_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(T_post, J,
                             std::numeric_limits<double>::quiet_NaN());
      new (&Y0_post_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y0_post_std_data__.data(),
        T_post, J);
      current_statement__ = 75;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 72;
        stan::model::assign(X_pre_std,
          stan::math::divide(
            stan::math::subtract(
              stan::model::rvalue(X_pre, "X_pre", stan::model::index_omni(),
                stan::model::index_uni(j)), mean_y), sd_y),
          "assigning variable X_pre_std", stan::model::index_omni(),
          stan::model::index_uni(j));
        current_statement__ = 73;
        stan::model::assign(Y0_post_std,
          stan::math::divide(
            stan::math::subtract(
              stan::model::rvalue(Y0_post, "Y0_post",
                stan::model::index_omni(), stan::model::index_uni(j)), mean_y),
            sd_y), "assigning variable Y0_post_std",
          stan::model::index_omni(), stan::model::index_uni(j));
      }
      current_statement__ = 76;
      stan::math::validate_non_negative_index("X_cov0_std", "K_cov", K_cov);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("X_cov0_std", "J", J);
      current_statement__ = 78;
      X_cov0_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(K_cov, J,
                            std::numeric_limits<double>::quiet_NaN());
      new (&X_cov0_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_cov0_std_data__.data(),
        K_cov, J);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("X_cov1_std", "K_cov", K_cov);
      current_statement__ = 80;
      X_cov1_std_data__ = Eigen::Matrix<double,-1,1>::Constant(K_cov,
                            std::numeric_limits<double>::quiet_NaN());
      new (&X_cov1_std)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(X_cov1_std_data__.data(),
        K_cov);
      current_statement__ = 91;
      for (int k = 1; k <= K_cov; ++k) {
        double m_k = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 81;
        m_k = stan::math::mean(
                stan::model::rvalue(X_cov0, "X_cov0",
                  stan::model::index_uni(k), stan::model::index_omni()));
        double s_k = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 82;
        s_k = stan::math::sd(
                stan::model::rvalue(X_cov0, "X_cov0",
                  stan::model::index_uni(k), stan::model::index_omni()));
        current_statement__ = 89;
        if (stan::math::logical_gt(s_k, 1e-12)) {
          current_statement__ = 86;
          stan::model::assign(X_cov0_std,
            stan::math::divide(
              stan::math::subtract(
                stan::model::rvalue(X_cov0, "X_cov0",
                  stan::model::index_uni(k), stan::model::index_omni()), m_k),
              s_k), "assigning variable X_cov0_std",
            stan::model::index_uni(k), stan::model::index_omni());
          current_statement__ = 87;
          stan::model::assign(X_cov1_std,
            ((stan::model::rvalue(X_cov1, "X_cov1", stan::model::index_uni(k))
            - m_k) / s_k), "assigning variable X_cov1_std",
            stan::model::index_uni(k));
        } else {
          current_statement__ = 83;
          stan::model::assign(X_cov0_std, stan::math::rep_row_vector(0.0, J),
            "assigning variable X_cov0_std", stan::model::index_uni(k),
            stan::model::index_omni());
          current_statement__ = 84;
          stan::model::assign(X_cov1_std, 0.0,
            "assigning variable X_cov1_std", stan::model::index_uni(k));
        }
      }
      current_statement__ = 92;
      stan::math::validate_non_negative_index("s", "J", J);
      current_statement__ = 93;
      s_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                   std::numeric_limits<double>::quiet_NaN());
      new (&s) Eigen::Map<Eigen::Matrix<double,-1,1>>(s_data__.data(), J);
      current_statement__ = 93;
      stan::model::assign(s,
        stan::math::multiply(rho,
          stan::math::mdivide_left(
            stan::math::subtract(I_J, stan::math::multiply(rho, W_J)), w_J1)),
        "assigning variable s");
      current_statement__ = 94;
      stan::math::validate_non_negative_index("s_abs", "J", J);
      current_statement__ = 95;
      s_abs_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&s_abs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(s_abs_data__.data(), J);
      current_statement__ = 95;
      stan::model::assign(s_abs, stan::math::fabs(s),
        "assigning variable s_abs");
      current_statement__ = 96;
      n_eff = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 96;
      n_eff = (T0 + stan::math::sum(v_cov));
      current_statement__ = 97;
      sigma_floor = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 97;
      sigma_floor = 0.05;
      current_statement__ = 98;
      lambda_tilde = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 98;
      lambda_tilde = ((lambda * n_eff) / stan::math::square(sigma_ref));
      current_statement__ = 99;
      stan::math::validate_positive_index("w", "J", J);
      current_statement__ = 100;
      stan::math::validate_non_negative_index("y_sim_pre", "T0", T0);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("y_counterfactual", "T_post",
        T_post);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (J - 1) + 1;
  }
  inline std::string model_name() const final {
    return "model_stan_2_NASC";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 1;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      local_scalar_t__ sigma_raw = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_raw = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 3;
      sigma_sc = stan::math::sqrt((stan::math::square(sigma_floor) +
                   stan::math::square(sigma_raw)));
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "sigma_sc", sigma_sc, 0);
      {
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_raw, 0, 1));
        current_statement__ = 19;
        if (use_penalty) {
          current_statement__ = 18;
          lp_accum__.add((-lambda_tilde * stan::math::dot_product(w, s_abs)));
        }
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<false>(y_pre_std,
                         stan::math::multiply(X_pre_std, w), sigma_sc));
        current_statement__ = 24;
        for (int k = 1; k <= K_cov; ++k) {
          current_statement__ = 22;
          if (stan::math::logical_gt(
                stan::model::rvalue(v_cov, "v_cov", stan::model::index_uni(k)),
                0)) {
            current_statement__ = 21;
            lp_accum__.add(stan::math::normal_lpdf<false>(
                             stan::model::rvalue(X_cov1_std, "X_cov1_std",
                               stan::model::index_uni(k)),
                             stan::math::dot_product(
                               stan::model::rvalue(X_cov0_std, "X_cov0_std",
                                 stan::model::index_uni(k),
                                 stan::model::index_omni()), w), (sigma_sc /
                             stan::math::sqrt(
                               stan::model::rvalue(v_cov, "v_cov",
                                 stan::model::index_uni(k))))));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> w =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      double sigma_raw = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma_raw = in__.template read_constrain_lb<local_scalar_t__,
                    jacobian__>(0, lp__);
      double sigma_sc = std::numeric_limits<double>::quiet_NaN();
      out__.write(w);
      out__.write(sigma_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      sigma_sc = stan::math::sqrt((stan::math::square(sigma_floor) +
                   stan::math::square(sigma_raw)));
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "sigma_sc", sigma_sc, 0);
      if (emit_transformed_parameters__) {
        out__.write(sigma_sc);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> y_sim_pre =
        Eigen::Matrix<double,-1,1>::Constant(T0,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> y_counterfactual =
        Eigen::Matrix<double,-1,1>::Constant(T_post,
          std::numeric_limits<double>::quiet_NaN());
      double wts_dot = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      wts_dot = stan::math::dot_product(w, s);
      double bias_correction = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      bias_correction = (stan::math::logical_eq(use_bias_correction, 1) ? (1.0
        / (1.0 - wts_dot)) : 1.0);
      current_statement__ = 14;
      for (int t = 1; t <= T0; ++t) {
        current_statement__ = 13;
        stan::model::assign(y_sim_pre,
          ((stan::math::normal_rng(
              stan::math::dot_product(
                stan::model::rvalue(X_pre_std, "X_pre_std",
                  stan::model::index_uni(t), stan::model::index_omni()), w),
              sigma_sc, base_rng__) * sd_y) + mean_y),
          "assigning variable y_sim_pre", stan::model::index_uni(t));
      }
      current_statement__ = 16;
      for (int t = 1; t <= T_post; ++t) {
        current_statement__ = 15;
        stan::model::assign(y_counterfactual,
          ((stan::math::normal_rng(
              stan::math::dot_product(
                stan::model::rvalue(Y0_post_std, "Y0_post_std",
                  stan::model::index_uni(t), stan::model::index_omni()), w),
              sigma_sc, base_rng__) * sd_y) + mean_y),
          "assigning variable y_counterfactual", stan::model::index_uni(t));
      }
      double lambda_tilde_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      lambda_tilde_out = lambda_tilde;
      double lambda_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      lambda_out = lambda;
      double n_eff_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 10;
      n_eff_out = n_eff;
      double sigma_sc_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 11;
      sigma_sc_out = sigma_sc;
      double sigma_ref_out = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 12;
      sigma_ref_out = sigma_ref;
      out__.write(y_sim_pre);
      out__.write(y_counterfactual);
      out__.write(wts_dot);
      out__.write(bias_correction);
      out__.write(lambda_tilde_out);
      out__.write(lambda_out);
      out__.write(n_eff_out);
      out__.write(sigma_sc_out);
      out__.write(sigma_ref_out);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(w,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable w");
      out__.write_free_simplex(w);
      local_scalar_t__ sigma_raw = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_raw = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_raw",
        "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 1;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(w);
      local_scalar_t__ sigma_raw = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_raw = context__.vals_r("sigma_raw")[(1 - 1)];
      out__.write_free_lb(0, sigma_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"w", "sigma_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"sigma_sc"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"y_sim_pre", "y_counterfactual", "wts_dot", "bias_correction",
             "lambda_tilde_out", "lambda_out", "n_eff_out", "sigma_sc_out",
             "sigma_ref_out"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(J)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T0)},
             std::vector<size_t>{static_cast<size_t>(T_post)},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}, std::vector<size_t>{},
             std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_raw");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma_sc");
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_sim_pre" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_counterfactual" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "wts_dot");
      param_names__.emplace_back(std::string() + "bias_correction");
      param_names__.emplace_back(std::string() + "lambda_tilde_out");
      param_names__.emplace_back(std::string() + "lambda_out");
      param_names__.emplace_back(std::string() + "n_eff_out");
      param_names__.emplace_back(std::string() + "sigma_sc_out");
      param_names__.emplace_back(std::string() + "sigma_ref_out");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (J - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_raw");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma_sc");
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_sim_pre" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_counterfactual" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "wts_dot");
      param_names__.emplace_back(std::string() + "bias_correction");
      param_names__.emplace_back(std::string() + "lambda_tilde_out");
      param_names__.emplace_back(std::string() + "lambda_out");
      param_names__.emplace_back(std::string() + "n_eff_out");
      param_names__.emplace_back(std::string() + "sigma_sc_out");
      param_names__.emplace_back(std::string() + "sigma_ref_out");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"sigma_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim_pre\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"generated_quantities\"},{\"name\":\"y_counterfactual\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"wts_dot\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda_tilde_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"n_eff_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_sc_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_ref_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((J -1)) + "},\"block\":\"parameters\"},{\"name\":\"sigma_raw\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"y_sim_pre\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"generated_quantities\"},{\"name\":\"y_counterfactual\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"wts_dot\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda_tilde_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"lambda_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"n_eff_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_sc_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma_ref_out\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (J + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (((((((((T0
      + T_post) + 1) + 1) + 1) + 1) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (J + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (((((((((T0
      + T_post) + 1) + 1) + 1) + 1) + 1) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stan_2_NASC_namespace::model_stan_2_NASC;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stan_2_NASC_namespace::profiles__;
}
#endif
#endif
