// Generated by rstantools.  Do not edit by hand.

/*
    nasc is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    nasc is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with nasc.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_stan_2_NASC_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 71> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 55, column 2 to column 15)",
  " (in 'string', line 56, column 2 to column 25)",
  " (in 'string', line 57, column 2 to column 23)",
  " (in 'string', line 69, column 2 to column 23)",
  " (in 'string', line 70, column 2 to column 34)",
  " (in 'string', line 71, column 2 to column 35)",
  " (in 'string', line 74, column 2 to column 80)",
  " (in 'string', line 76, column 4 to column 88)",
  " (in 'string', line 75, column 18 to line 77, column 3)",
  " (in 'string', line 75, column 2 to line 77, column 3)",
  " (in 'string', line 79, column 4 to column 97)",
  " (in 'string', line 78, column 22 to line 80, column 3)",
  " (in 'string', line 78, column 2 to line 80, column 3)",
  " (in 'string', line 61, column 2 to column 26)",
  " (in 'string', line 62, column 2 to column 25)",
  " (in 'string', line 64, column 2 to column 44)",
  " (in 'string', line 66, column 2 to column 61)",
  " (in 'string', line 13, column 2 to column 17)",
  " (in 'string', line 14, column 2 to column 18)",
  " (in 'string', line 15, column 9 to column 14)",
  " (in 'string', line 15, column 16 to column 18)",
  " (in 'string', line 15, column 2 to column 28)",
  " (in 'string', line 16, column 9 to column 10)",
  " (in 'string', line 16, column 12 to column 13)",
  " (in 'string', line 16, column 2 to column 19)",
  " (in 'string', line 17, column 9 to column 10)",
  " (in 'string', line 17, column 2 to column 17)",
  " (in 'string', line 18, column 2 to column 22)",
  " (in 'string', line 19, column 9 to column 15)",
  " (in 'string', line 19, column 17 to column 18)",
  " (in 'string', line 19, column 2 to column 28)",
  " (in 'string', line 20, column 9 to column 15)",
  " (in 'string', line 20, column 2 to column 25)",
  " (in 'string', line 22, column 2 to column 30)",
  " (in 'string', line 25, column 2 to column 44)",
  " (in 'string', line 28, column 9 to column 10)",
  " (in 'string', line 28, column 12 to column 13)",
  " (in 'string', line 28, column 2 to column 53)",
  " (in 'string', line 32, column 9 to column 11)",
  " (in 'string', line 32, column 2 to column 49)",
  " (in 'string', line 33, column 2 to column 28)",
  " (in 'string', line 34, column 2 to column 26)",
  " (in 'string', line 35, column 9 to column 11)",
  " (in 'string', line 35, column 2 to column 49)",
  " (in 'string', line 37, column 9 to column 11)",
  " (in 'string', line 37, column 13 to column 14)",
  " (in 'string', line 37, column 2 to column 40)",
  " (in 'string', line 38, column 9 to column 11)",
  " (in 'string', line 38, column 13 to column 14)",
  " (in 'string', line 38, column 2 to column 26)",
  " (in 'string', line 39, column 9 to column 15)",
  " (in 'string', line 39, column 17 to column 18)",
  " (in 'string', line 39, column 2 to column 32)",
  " (in 'string', line 40, column 9 to column 10)",
  " (in 'string', line 40, column 2 to column 19)",
  " (in 'string', line 41, column 9 to column 10)",
  " (in 'string', line 41, column 2 to column 17)",
  " (in 'string', line 43, column 4 to column 33)",
  " (in 'string', line 44, column 4 to column 31)",
  " (in 'string', line 45, column 4 to column 56)",
  " (in 'string', line 46, column 4 to column 60)",
  " (in 'string', line 42, column 17 to line 47, column 3)",
  " (in 'string', line 42, column 2 to line 47, column 3)",
  " (in 'string', line 51, column 9 to column 10)",
  " (in 'string', line 51, column 2 to column 58)",
  " (in 'string', line 52, column 9 to column 10)",
  " (in 'string', line 52, column 2 to column 28)",
  " (in 'string', line 55, column 10 to column 11)",
  " (in 'string', line 69, column 9 to column 11)",
  " (in 'string', line 70, column 9 to column 15)"};
#include <stan_meta_header.hpp>
class model_stan_2_NASC final : public model_base_crtp<model_stan_2_NASC> {
private:
  int J;
  int T0;
  Eigen::Matrix<double,-1,-1> Y_panel_data__;
  Eigen::Matrix<double,-1,-1> W_J_data__;
  Eigen::Matrix<double,-1,1> w_J1_data__;
  int T_post;
  Eigen::Matrix<double,-1,-1> Y0_post_data__;
  Eigen::Matrix<double,-1,1> Y1_post_data__;
  double rho;
  int use_bias_correction;
  Eigen::Matrix<double,-1,-1> I_J_data__;
  Eigen::Matrix<double,-1,1> y_pre_data__;
  double mean_y;
  double sd_y;
  Eigen::Matrix<double,-1,1> y_pre_std_data__;
  Eigen::Matrix<double,-1,-1> X_pre_data__;
  Eigen::Matrix<double,-1,-1> X_pre_std_data__;
  Eigen::Matrix<double,-1,-1> Y0_post_std_data__;
  Eigen::Matrix<double,-1,1> mean_x_data__;
  Eigen::Matrix<double,-1,1> sd_x_data__;
  Eigen::Matrix<double,-1,1> s_data__;
  Eigen::Matrix<double,-1,1> s_abs_data__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y_panel{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> W_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> w_J1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y0_post{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> Y1_post{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> I_J{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y_pre{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> y_pre_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_pre{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X_pre_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y0_post_std{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> mean_x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> sd_x{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> s{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> s_abs{nullptr, 0};
public:
  ~model_stan_2_NASC() {}
  model_stan_2_NASC(stan::io::var_context& context__, unsigned int
                    random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::model_stan_2_NASC";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 18;
      context__.validate_dims("data initialization", "J", "int",
        std::vector<size_t>{});
      J = std::numeric_limits<int>::min();
      current_statement__ = 18;
      J = context__.vals_i("J")[(1 - 1)];
      current_statement__ = 18;
      stan::math::check_greater_or_equal(function__, "J", J, 0);
      current_statement__ = 19;
      context__.validate_dims("data initialization", "T0", "int",
        std::vector<size_t>{});
      T0 = std::numeric_limits<int>::min();
      current_statement__ = 19;
      T0 = context__.vals_i("T0")[(1 - 1)];
      current_statement__ = 19;
      stan::math::check_greater_or_equal(function__, "T0", T0, 1);
      current_statement__ = 20;
      stan::math::validate_non_negative_index("Y_panel", "J + 1", (J + 1));
      current_statement__ = 21;
      stan::math::validate_non_negative_index("Y_panel", "T0", T0);
      current_statement__ = 22;
      context__.validate_dims("data initialization", "Y_panel", "double",
        std::vector<size_t>{static_cast<size_t>((J + 1)),
          static_cast<size_t>(T0)});
      Y_panel_data__ = Eigen::Matrix<double,-1,-1>::Constant((J + 1), T0,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y_panel)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_panel_data__.data(), (J +
        1), T0);
      {
        std::vector<local_scalar_t__> Y_panel_flat__;
        current_statement__ = 22;
        Y_panel_flat__ = context__.vals_r("Y_panel");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
          current_statement__ = 22;
          for (int sym2__ = 1; sym2__ <= (J + 1); ++sym2__) {
            current_statement__ = 22;
            stan::model::assign(Y_panel, Y_panel_flat__[(pos__ - 1)],
              "assigning variable Y_panel", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 22;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 23;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("W_J", "J", J);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "W_J", "double",
        std::vector<size_t>{static_cast<size_t>(J), static_cast<size_t>(J)});
      W_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&W_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(W_J_data__.data(),
        J, J);
      {
        std::vector<local_scalar_t__> W_J_flat__;
        current_statement__ = 25;
        W_J_flat__ = context__.vals_r("W_J");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 25;
          for (int sym2__ = 1; sym2__ <= J; ++sym2__) {
            current_statement__ = 25;
            stan::model::assign(W_J, W_J_flat__[(pos__ - 1)],
              "assigning variable W_J", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 25;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 26;
      stan::math::validate_non_negative_index("w_J1", "J", J);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "w_J1", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      w_J1_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                      std::numeric_limits<double>::quiet_NaN());
      new (&w_J1) Eigen::Map<Eigen::Matrix<double,-1,1>>(w_J1_data__.data(),
        J);
      {
        std::vector<local_scalar_t__> w_J1_flat__;
        current_statement__ = 27;
        w_J1_flat__ = context__.vals_r("w_J1");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 27;
          stan::model::assign(w_J1, w_J1_flat__[(pos__ - 1)],
            "assigning variable w_J1", stan::model::index_uni(sym1__));
          current_statement__ = 27;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 28;
      context__.validate_dims("data initialization", "T_post", "int",
        std::vector<size_t>{});
      T_post = std::numeric_limits<int>::min();
      current_statement__ = 28;
      T_post = context__.vals_i("T_post")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "T_post", T_post, 1);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("Y0_post", "T_post", T_post);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("Y0_post", "J", J);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "Y0_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post),
          static_cast<size_t>(J)});
      Y0_post_data__ = Eigen::Matrix<double,-1,-1>::Constant(T_post, J,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y0_post)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y0_post_data__.data(),
        T_post, J);
      {
        std::vector<local_scalar_t__> Y0_post_flat__;
        current_statement__ = 31;
        Y0_post_flat__ = context__.vals_r("Y0_post");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 31;
          for (int sym2__ = 1; sym2__ <= T_post; ++sym2__) {
            current_statement__ = 31;
            stan::model::assign(Y0_post, Y0_post_flat__[(pos__ - 1)],
              "assigning variable Y0_post", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 31;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("Y1_post", "T_post", T_post);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "Y1_post", "double",
        std::vector<size_t>{static_cast<size_t>(T_post)});
      Y1_post_data__ = Eigen::Matrix<double,-1,1>::Constant(T_post,
                         std::numeric_limits<double>::quiet_NaN());
      new (&Y1_post)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(Y1_post_data__.data(), T_post);
      {
        std::vector<local_scalar_t__> Y1_post_flat__;
        current_statement__ = 33;
        Y1_post_flat__ = context__.vals_r("Y1_post");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(Y1_post, Y1_post_flat__[(pos__ - 1)],
            "assigning variable Y1_post", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      context__.validate_dims("data initialization", "rho", "double",
        std::vector<size_t>{});
      rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 34;
      rho = context__.vals_r("rho")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "rho", rho, -1);
      current_statement__ = 34;
      stan::math::check_less_or_equal(function__, "rho", rho, 1);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "use_bias_correction",
        "int", std::vector<size_t>{});
      use_bias_correction = std::numeric_limits<int>::min();
      current_statement__ = 35;
      use_bias_correction = context__.vals_i("use_bias_correction")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "use_bias_correction",
        use_bias_correction, 0);
      current_statement__ = 35;
      stan::math::check_less_or_equal(function__, "use_bias_correction",
        use_bias_correction, 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("I_J", "J", J);
      current_statement__ = 38;
      I_J_data__ = Eigen::Matrix<double,-1,-1>::Constant(J, J,
                     std::numeric_limits<double>::quiet_NaN());
      new (&I_J) Eigen::Map<Eigen::Matrix<double,-1,-1>>(I_J_data__.data(),
        J, J);
      current_statement__ = 38;
      stan::model::assign(I_J,
        stan::math::diag_matrix(stan::math::rep_vector(1.0, J)),
        "assigning variable I_J");
      current_statement__ = 39;
      stan::math::validate_non_negative_index("y_pre", "T0", T0);
      current_statement__ = 40;
      y_pre_data__ = Eigen::Matrix<double,-1,1>::Constant(T0,
                       std::numeric_limits<double>::quiet_NaN());
      new (&y_pre)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(y_pre_data__.data(), T0);
      current_statement__ = 40;
      stan::model::assign(y_pre,
        stan::math::to_vector(
          stan::model::rvalue(Y_panel, "Y_panel",
            stan::model::index_uni((J + 1)), stan::model::index_omni())),
        "assigning variable y_pre");
      current_statement__ = 41;
      mean_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      mean_y = stan::math::mean(y_pre);
      current_statement__ = 42;
      sd_y = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 42;
      sd_y = stan::math::sd(y_pre);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("y_pre_std", "T0", T0);
      current_statement__ = 44;
      y_pre_std_data__ = Eigen::Matrix<double,-1,1>::Constant(T0,
                           std::numeric_limits<double>::quiet_NaN());
      new (&y_pre_std)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(y_pre_std_data__.data(), T0);
      current_statement__ = 44;
      stan::model::assign(y_pre_std,
        stan::math::divide(stan::math::subtract(y_pre, mean_y), sd_y),
        "assigning variable y_pre_std");
      current_statement__ = 45;
      stan::math::validate_non_negative_index("X_pre", "T0", T0);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("X_pre", "J", J);
      current_statement__ = 47;
      X_pre_data__ = Eigen::Matrix<double,-1,-1>::Constant(T0, J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&X_pre)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_pre_data__.data(), T0, J);
      current_statement__ = 47;
      stan::model::assign(X_pre,
        stan::math::transpose(
          stan::model::rvalue(Y_panel, "Y_panel",
            stan::model::index_min_max(1, J), stan::model::index_omni())),
        "assigning variable X_pre");
      current_statement__ = 48;
      stan::math::validate_non_negative_index("X_pre_std", "T0", T0);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("X_pre_std", "J", J);
      current_statement__ = 50;
      X_pre_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(T0, J,
                           std::numeric_limits<double>::quiet_NaN());
      new (&X_pre_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_pre_std_data__.data(), T0,
        J);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("Y0_post_std", "T_post", T_post);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("Y0_post_std", "J", J);
      current_statement__ = 53;
      Y0_post_std_data__ = Eigen::Matrix<double,-1,-1>::Constant(T_post, J,
                             std::numeric_limits<double>::quiet_NaN());
      new (&Y0_post_std)
        Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y0_post_std_data__.data(),
        T_post, J);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("mean_x", "J", J);
      current_statement__ = 55;
      mean_x_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                        std::numeric_limits<double>::quiet_NaN());
      new (&mean_x)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(mean_x_data__.data(), J);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("sd_x", "J", J);
      current_statement__ = 57;
      sd_x_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                      std::numeric_limits<double>::quiet_NaN());
      new (&sd_x) Eigen::Map<Eigen::Matrix<double,-1,1>>(sd_x_data__.data(),
        J);
      current_statement__ = 63;
      for (int j = 1; j <= J; ++j) {
        current_statement__ = 58;
        stan::model::assign(mean_x,
          stan::math::mean(
            stan::model::rvalue(X_pre, "X_pre", stan::model::index_omni(),
              stan::model::index_uni(j))), "assigning variable mean_x",
          stan::model::index_uni(j));
        current_statement__ = 59;
        stan::model::assign(sd_x,
          stan::math::sd(
            stan::model::rvalue(X_pre, "X_pre", stan::model::index_omni(),
              stan::model::index_uni(j))), "assigning variable sd_x",
          stan::model::index_uni(j));
        current_statement__ = 60;
        stan::model::assign(X_pre_std,
          stan::math::divide(
            stan::math::subtract(
              stan::model::rvalue(X_pre, "X_pre", stan::model::index_omni(),
                stan::model::index_uni(j)),
              stan::model::rvalue(mean_x, "mean_x", stan::model::index_uni(j))),
            stan::model::rvalue(sd_x, "sd_x", stan::model::index_uni(j))),
          "assigning variable X_pre_std", stan::model::index_omni(),
          stan::model::index_uni(j));
        current_statement__ = 61;
        stan::model::assign(Y0_post_std,
          stan::math::divide(
            stan::math::subtract(
              stan::model::rvalue(Y0_post, "Y0_post",
                stan::model::index_omni(), stan::model::index_uni(j)),
              stan::model::rvalue(mean_x, "mean_x", stan::model::index_uni(j))),
            stan::model::rvalue(sd_x, "sd_x", stan::model::index_uni(j))),
          "assigning variable Y0_post_std", stan::model::index_omni(),
          stan::model::index_uni(j));
      }
      current_statement__ = 64;
      stan::math::validate_non_negative_index("s", "J", J);
      current_statement__ = 65;
      s_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                   std::numeric_limits<double>::quiet_NaN());
      new (&s) Eigen::Map<Eigen::Matrix<double,-1,1>>(s_data__.data(), J);
      current_statement__ = 65;
      stan::model::assign(s,
        stan::math::multiply(rho,
          stan::math::mdivide_left(
            stan::math::subtract(I_J, stan::math::multiply(rho, W_J)), w_J1)),
        "assigning variable s");
      current_statement__ = 66;
      stan::math::validate_non_negative_index("s_abs", "J", J);
      current_statement__ = 67;
      s_abs_data__ = Eigen::Matrix<double,-1,1>::Constant(J,
                       std::numeric_limits<double>::quiet_NaN());
      new (&s_abs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(s_abs_data__.data(), J);
      current_statement__ = 67;
      stan::model::assign(s_abs, stan::math::fabs(s),
        "assigning variable s_abs");
      current_statement__ = 68;
      stan::math::validate_positive_index("w", "J", J);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("y_sim_pre", "T0", T0);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("y_counterfactual", "T_post",
        T_post);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (J - 1) + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_stan_2_NASC";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 1;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_sc = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 3;
      lambda = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      {
        current_statement__ = 14;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma_sc, 0, 1));
        current_statement__ = 15;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(lambda, 1, 1));
        current_statement__ = 16;
        lp_accum__.add((-lambda * stan::math::dot_product(w, s_abs)));
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<false>(y_pre_std,
                         stan::math::multiply(X_pre_std, w), sigma_sc));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_stan_2_NASC_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> w =
        Eigen::Matrix<double,-1,1>::Constant(J,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      w = in__.template read_constrain_simplex<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(lp__, J);
      double sigma_sc = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma_sc = in__.template read_constrain_lb<local_scalar_t__,
                   jacobian__>(0, lp__);
      double lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      lambda = in__.template read_constrain_lb<local_scalar_t__,
                 jacobian__>(0, lp__);
      out__.write(w);
      out__.write(sigma_sc);
      out__.write(lambda);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> y_sim_pre =
        Eigen::Matrix<double,-1,1>::Constant(T0,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> y_counterfactual =
        Eigen::Matrix<double,-1,1>::Constant(T_post,
          std::numeric_limits<double>::quiet_NaN());
      double wts_dot = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      wts_dot = stan::math::dot_product(w, s);
      double bias_correction = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      bias_correction = (stan::math::logical_eq(use_bias_correction, 1) ? (1.0
        / (1.0 - wts_dot)) : 1.0);
      current_statement__ = 10;
      for (int t = 1; t <= T0; ++t) {
        current_statement__ = 8;
        stan::model::assign(y_sim_pre,
          ((stan::math::normal_rng(
              stan::math::dot_product(
                stan::model::rvalue(X_pre_std, "X_pre_std",
                  stan::model::index_uni(t), stan::model::index_omni()), w),
              sigma_sc, base_rng__) * sd_y) + mean_y),
          "assigning variable y_sim_pre", stan::model::index_uni(t));
      }
      current_statement__ = 13;
      for (int t = 1; t <= T_post; ++t) {
        current_statement__ = 11;
        stan::model::assign(y_counterfactual,
          ((stan::math::normal_rng(
              stan::math::dot_product(
                stan::model::rvalue(Y0_post_std, "Y0_post_std",
                  stan::model::index_uni(t), stan::model::index_omni()), w),
              sigma_sc, base_rng__) * sd_y) + mean_y),
          "assigning variable y_counterfactual", stan::model::index_uni(t));
      }
      out__.write(y_sim_pre);
      out__.write(y_counterfactual);
      out__.write(wts_dot);
      out__.write(bias_correction);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(w,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(J),
        "assigning variable w");
      out__.write_free_simplex(w);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_sc = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma_sc);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 3;
      lambda = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(J)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma_sc",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> w =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(J, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 1;
        w_flat__ = context__.vals_r("w");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_simplex(w);
      local_scalar_t__ sigma_sc = DUMMY_VAR__;
      current_statement__ = 2;
      sigma_sc = context__.vals_r("sigma_sc")[(1 - 1)];
      out__.write_free_lb(0, sigma_sc);
      local_scalar_t__ lambda = DUMMY_VAR__;
      current_statement__ = 3;
      lambda = context__.vals_r("lambda")[(1 - 1)];
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"w", "sigma_sc", "lambda"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string>
        temp{"y_sim_pre", "y_counterfactual", "wts_dot", "bias_correction"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(J)},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T0)},
             std::vector<size_t>{static_cast<size_t>(T_post)},
             std::vector<size_t>{}, std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= J; ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sc");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_sim_pre" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_counterfactual" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "wts_dot");
      param_names__.emplace_back(std::string() + "bias_correction");
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= (J - 1); ++sym1__) {
      param_names__.emplace_back(std::string() + "w" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma_sc");
    param_names__.emplace_back(std::string() + "lambda");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T0; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_sim_pre" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T_post; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_counterfactual" + '.' +
          std::to_string(sym1__));
      }
      param_names__.emplace_back(std::string() + "wts_dot");
      param_names__.emplace_back(std::string() + "bias_correction");
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(J) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_sim_pre\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"generated_quantities\"},{\"name\":\"y_counterfactual\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"wts_dot\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"w\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((J -1)) + "},\"block\":\"parameters\"},{\"name\":\"sigma_sc\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_sim_pre\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T0) + "},\"block\":\"generated_quantities\"},{\"name\":\"y_counterfactual\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T_post) + "},\"block\":\"generated_quantities\"},{\"name\":\"wts_dot\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"bias_correction\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((J + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((((T0 +
      T_post) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((J + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * ((((T0 +
      T_post) + 1) + 1));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_stan_2_NASC_namespace::model_stan_2_NASC;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_stan_2_NASC_namespace::profiles__;
}
#endif
#endif
